<?php
// $Id: be_by.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language: Belarusian
// ENCODING: CP1251
// AUTHOR: Andrei Dolgushin <mahadeo@tut.by>


$skin_beby = array( 

"label" => 
 array ( 
  "about" => "аб сэрвісе"
 ,"back" => "Назад"
 ,"changeLang" => "Зьмяніць мову"
 ,"date" => "Дата"
 ,"delete" => "Выдаліць"
 ,"doclick" => "клікніце"
 ,"enter" => "Наперад!"
 ,"feeds" => "Стужкі"
 ,"four" => "4"
 ,"from" => "Ад"
 ,"furtherHelp" => "Далейшая дапамога"
 ,"have" => "Маеце"
 ,"here" => "тут"
 ,"howto" => "Як карыстацца __PM__"
 ,"logout" => "Скончыць працу"
 ,"mails" => "лісты"
 ,"message" => "Ліст"
 ,"one" => "1"
 ,"please" => "Калі ласка"
 ,"save" => "захаваць"
 ,"step" => "Крок"
 ,"sorry" => "Выбачайце"
 ,"subject" => "Тэма"
 ,"three" => "3"
 ,"toretry" => "паспрабаваць ізноў"
 ,"two" => "2"
 ,"viewRawmail" => "Глядзець неапрацаваную пошту"
 ,"welcome" => "Ласкава запрашаем"
 ,"welcometo" => "Ласкава запрашаем да __PM__"
 )

, "locale" => 
 array (
  "charset" => "CP1251"
 ,"lang" => "be"
 )

, "help" => 
 array (
  "404" => "Вы зьвярнуліся да старонкі, якая не існуе!<p />Мажліва вам трэба распачаць з"
 ,"500" => "нашаму сэрверу не да спадобы ваш запыт ці нешта сапсавалася."
 ,"saveMail" => "Дазваляе захаваць гэты ліст ды імпаратваць у ваш улюбёны паштовы кліент"
 ,"viewMail" => "Можаце прагледзець зыходную неапрацаваную пошту"
 ,"deleteMail" => "Выдаляе ліст з сыстэмы"
 )

, "text" => 
 array ( 
  "about.feeds" => "Карыстацца стужкамі RSS 2.0 можна заўжды, калі прысутны памаранчавы лягатып <span class='rss'>RSS 2.0</span>."
 ,"about.feeds.url" => "Звычайны фармат url-адрэсы RSS - гэта <b>http://www.pookmail.com/rss/email_account.xml</b>"
 ,"about.feeds.aggregator" => " глядзець адну са стужак PookMail.com праз ваш <a href='http://en.wikipedia.org/wiki/News_aggregator'>RSS Агрэгатар</a>"
 ,"about.feeds.aggregatorStep1" => "Скапіюйце URL/скарачэньне, што адпявядае патрэбнай вам паштовай скрыні."
 ,"about.feeds.aggregatorStep2" => "Устаўце URL у ваш чытальнік."
 ,"about.furtherHelp" => "Калі ласка, дасылайце пытаньні, камэнтары, паведамленьні аб памылках ды ўсё астатняе непасрэдна да нас на <b><script type='text/javascript'>document.write(foo())</script></b>."
 ,"deleteKO" => "Нельга выдаліць ваш ліст"
 ,"deleteOK" => "Ваш ліст выдалены"
 ,"howtostep1" => "Замест таго каб аддаваць вашую э-пошту кожнаму ўэб-сайту на Зямлі, проста прыдумляеце сабе ўяўнае імя для <i>@pookmail.com</i>.<br />Напрыклад: <b>adczapisia@pookmail.com</b>"
 ,"howtostep2" => "Чакаеце, покуль прыйдзе жаданы ліст."
 ,"howtostep3" => "Уваходзіце на PookMail.com проста набраўшы вашае ўяўнае імя э-пошты (<b>adczapisia</b>) у форму уваходу, і цісьнеце <kbd>НАПЕРАД</kbd>"
 ,"howtostep4" => "Праз 24 гадзіны скрыня, прызначаная на вашае імя ўваходу, перастане існаваць у сыстэме."
 ,"whatispookmail" => "<b>PookMail.com</b> - гэта сыстэма <i>аднаразовых паштовых скрыняў</i>. Карыстайцеся PookMail.com калі не жадаеце аддаваць прыватную адрэсу э-пошты падазроным ўэб-сайтам.<p />Гэта надта ж <b>проста, ананімна і займальна</b>! Адно прыдумляеце імя ды НАПЕРАД!"
 ,"rsssubscription" => "Падпісацца на RSS-стужку PookMail, каб лісты прыходзілі проста на ваш працоўны стол!"
 ,"rss.desc" => "Стужка RSS з Pookmail.com дазваляе чытаць лісты, што прыходзяць на якую заўгодна скрыню PookMail."
 ,"request4trans" => "<b>Жадаеце пабачыць P<font color='red'>o</font><font color='blue'>o</font>kMail&#8482; на сваёй мове?</b> <br /><br /> Мы цікавыя да перакладчыкаў, што б дапамаглі нам перакласьці гэты сэрвіс на іншыя мовы. Калі вы гатовыя супрацоўнічаць, калі ласка дашліце ліст на <b><script type='text/javascript'>document.write(foo())</script></b>."
 ) 
);

  $langs["be_by"] = $skin_beby;
?>
