<?php
// $Id: bg.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language: Bulgarian 
// ENCODING: WINDOWS-1251
// AUTHOR: Peio Budakov <m_mimi_@abv.bg> 


$skin_bg = array( 

"label" => 
 array ( 
  "about" => "Относно"
 ,"back" => "Назад"
 ,"changeLang" => "Смяна на езика"
 ,"date" => "Дата"
 ,"delete" => "Изтриите"
 ,"doclick" => "натиснете"
 ,"enter" => "Давай!"
 ,"feeds" => "Feeds"
 ,"four" => "4"
 ,"from" => "От"
 ,"furtherHelp" => "Допълнителна помощ"
 ,"have" => "Вие имате"
 ,"here" => "Тук"
 ,"howto" => "Как да използваме __PM__"
 ,"logout" => "Излизане"
 ,"mails" => "Писма"
 ,"message" => "Съобщение"
 ,"one" => "1"
 ,"please" => "Моля"
 ,"save" => "Запаметяване"
 ,"step" => "Стъпка"
 ,"sorry" => "Съжаляваме"
 ,"subject" => "Относно"
 ,"three" => "3"
 ,"toretry" => "to retry"
 ,"two" => "2"
 ,"viewRawmail" => "View Raw Mail"
 ,"welcome" => "Добре дошли"
 ,"welcometo" => "Добре дошли в __PM__"
 )

, "locale" => 
 array (
  "charset" => "WINDOWS-1251"
 ,"lang" => "bg"
 )

, "help" => 
 array (
  "404" => "Страницата която търсите не е открита!<p />Perhaps you should start at"
 ,"500" => "Нашият сървър не хареса Вашата заявка или правите нещо погрешно."
 ,"saveMail" => "Можете да запаметите това писмо и да го импортирате във Вашата любима ем@йл програма "
 ,"viewMail" => "Вие може да видите оригиналното писмо"
 ,"deleteMail" => "Изтриване на писмото от сървъра"
 )

, "text" => 
 array ( 
  "about.feeds" => "RSS 2.0 feeds are available wherever you see an orange <span class='rss'>RSS 2.0</span> logo."
 ,"about.feeds.url" => "The general format of RSS urls is <b>http://www.pookmail.com/rss/email_account.xml</b>"
 ,"about.feeds.aggregator" => " view one of the PookMail.com feeds in your <a href='http://en.wikipedia.org/wiki/News_aggregator'>RSS Aggregator</a>"
 ,"about.feeds.aggregatorStep1" => "Copy the URL/shortcut that corresponds to the account that interests you."
 ,"about.feeds.aggregatorStep2" => "Paste the URL into your reader."
 ,"about.furtherHelp" => "Please send questions, comments, bug reports etc directly to us at <b><script type='text/javascript'>document.write(foo())</script></b>."
 ,"deleteKO" => "Вашият емайл не може да бъде изтрит!"
 ,"deleteOK" => "Вашият емайл беше изтрит успешно!"
 ,"howtostep1" => "Instead of giving your real email address to every website on Earth, just make up an imaginary name for <i>@pookmail.com</i>.<br />Example: <b>dontbotherme@pookmail.com</b>"
 ,"howtostep2" => "Изчакайте да пристигне писмото."
 ,"howtostep3" => "Влезте в PookMail.com като напишете някакъв емайл (<b>dontbotherme</b>) в логин формата, и натиснете <kbd>GO</kbd>"
 ,"howtostep4" => "След 24 часа, емайла асоцииран с това име ще бъде премахнат от сървъра."
 ,"whatispookmail" => "<b>PookMail.com</b> е <i>създаден за Ваше улеснение</i> . Използвайте PookMail.com за да избегнете даването на Персоналният Ви емайл на непознати web сайтове.<p />Това е <b>лесно, анонимно и забавно</b>! Само си измислете име и давайте!"
 ,"rsssubscription" => "Subscribe to PookMail's RSS feeds to get emails delivered directly to your desktop!"
 ,"rss.desc" => "Pookmail.com RSS feed allows you to know the incoming emails of any PookMail account."
 ,"request4trans" => "<b>Do you want to see P<font color='red'>o</font><font color='blue'>o</font>kMail&#8482; in your own language?</b> <br /><br /> We are looking for translators who would like to help us transtalating this service to others languages. If you like to collaborate, please send an email to <b><script type='text/javascript'>document.write(foo())</script></b>."
 ) 
);

  $langs["bg"] = $skin_bg;
?>
