<?php
// $Id: blank.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language: 
// ENCODING: 
// AUTHOR: 


$skin_XXX = array( 

"label" => 
 array ( 
  "about"   => ""
 ,"back"    => ""
 ,"changeLang" => ""
 ,"date"    => ""
 ,"delete"  => ""
 ,"doclick" => ""
 ,"enter"   => ""
 ,"feeds"   => ""
 ,"from"    => ""
 ,"furtherHelp" => ""
 ,"have"    => ""
 ,"here"    => ""
 ,"howto"   => ""
 ,"international"   => ""
 ,"logout"  => ""
 ,"mails"   => ""
 ,"message" => ""
 ,"please"  => ""
 ,"save"    => ""
 ,"step"    => ""
 ,"sorry"   => ""
 ,"subject" => ""
 ,"toretry" => ""
 ,"viewRawmail" => ""
 ,"welcome" => ""
 ,"welcometo" => ""
 )

, "locale" => 
 array (
  "charset" => ""
 ,"lang" => ""
 )

, "help" => 
 array (
  "404" => ""
 ,"500" => ""
 ,"saveMail" => ""
 ,"viewMail" => ""
 ,"deleteMail" => ""
 )

, "text" => 
 array ( 
  "about.feeds" => ""
 ,"about.feeds.url" => ""
 ,"about.feeds.aggregator" => ""
 ,"about.feeds.aggregatorStep1" => ""
 ,"about.feeds.aggregatorStep2" => ""
 ,"about.furtherHelp" => ""
 ,"deleteKO" => ""
 ,"deleteOK" => ""
 ,"howtostep1" => ""
 ,"howtostep2" => ""
 ,"howtostep3" => ""
 ,"howtostep4" => ""
 ,"whatispookmail" => ""
 ,"rsssubscription" => ""
 ,"rss.desc" => ""
 ,"request4trans" => ""
 ) 
);

  $langs["XXX"] = $skin_XXX;
?>
