<?php
// $Id: ca.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language: Catala
// ENCODING: ISO-88591
// AUTHOR: Josep Camos <vueloavutarda@wanadoo.es>


$skin_ca = array( 

"label" => 
 array ( 
 "about" => "sobre"
,"availableIn" => "__PM_ també es pot trobar a ..."
,"back" => "Tornar"
,"comingsoon" => "Ben aviat"
,"changeLang" => "Canviar d'idioma"
,"date" => "Data"
,"delete" => "Esborrar"
,"doclick" => "Clicar"
,"enter" => "Entrar"
,"feeds" => "Feeds"
,"four" => "4"
,"from" => "De"
,"furtherHelp" => "Més ajuda"
,"have" => "Tens"
,"here" => "aquí"
,"howto" => "Com fer servir __PM__"
,"international" => "internacional"
,"logout" => "Sortir"
,"mails" => "missatges"
,"message" => "missatge"
,"one" => "1"
,"please" => "Sisplau"
,"save" => "Guardar"
,"step" => "pas"
,"sorry" => "Ho sento"
,"subject" => "Assumpte"
,"thanksTranslators" => "Agraïment especial als traductors"
,"three" => "3"
,"toretry" => "Reintentar-ho"
,"two" => "2"
,"viewRawmail" => "Veure format raw"
,"welcome" => "Benvinguts"
,"welcometo" => "Benvinguts a __PM__"
 )

, "locale" => 
 array (
  "charset" => "ISO-8859-1"
 ,"lang" => "ca"
 )

, "help" => 
 array (
 "404" => "No sé què buscaves, però per aquí no hi és. <p />Mirar d'anar a "
,"500" => "O el nostre servidor passa de la teva consulta o aquí hi ha alguna cosa que no funciona."
,"saveMail" => "Et permet gravar aquest correu per importar-lo amb el teu client de correu favorit"
,"viewMail" => "Pots veure el missatge original en format raw"
,"deleteMail" => "Esborra el correu del sistema"
 )

, "text" => 
 array ( 
 "about.feeds" => "La sindicació en RSS 2.0 està disponible allà on vegis el logotip <span class='rss'>RSS 2.0</span>."
,"about.feeds.url" => "El format general de la URL per RSS és <b>http://www.pookmail.com/rss/compte_de_correu.xml</b>"
,"about.feeds.aggregator" => " Per veure un dels feeds de PookMail.com al teu agregador de RSS:"
,"about.feeds.aggregatorStep1" => "Copia la URL que correspon al compte que t'interessa."
,"about.feeds.aggregatorStep2" => "Enganxa la URL al teu lector."
,"about.furtherHelp" => "Envia'ns les teves preguntes, comentaris, suggeriments, <i>bugs</i> que detectis, etc. directament a nosaltres: <b><script type='text/javascript'>document.write(foo())</script></b>."
,"about.visitBlog" => "Visita <a id='blog' href='http://pookmail.blogspot.com'>El Blog de PookMail.com</a> per estar a l'aguait de l'última notícia."
,"deleteKO" => "El teu correu no es pot esborrar"
,"deleteOK" => "El teu correu ha estat esborrat"
,"dbm.subject" => "Compte d'exemple"
,"dbm.body" => "Aquest compte és només un exemple. Per la teva seguretat no permetem enviar o llegir correus des d'aquest compte. Sisplau, prova'n un altre. <p />Gràcies."
,"howtostep1" => "Quan et demanin una adreça de correu, en comptes de donar la teva adreça real n'hi ha prou amb què t'inventis un nom d'usuari acabat en <i>@pookmail.com</i>.<br />Per exemple: <b>noemprenyeu@pookmail.com</b>"
,"howtostep2" => "Deixa un temps de marge perquè arribi el teu correu a <b>PookMail.com</b>"
,"howtostep3" => "Entra a <b>PookMail.com</b> posant el teu nom d'usuari inventat (<b>noemprenyeu</b>) en el formulari, i fes clic a <kbd>Entrar</kbd>"
,"howtostep4" => "Passades 24 hores, el missatge associat al teu nom d'usuari serà esborrat del sistema de forma automàtica."
,"whatispookmail" => "<b>PookMail.com</b> és un sistema de comptes de correu <i>d'un sol ús</i>. Fes servir PookMail.com per estalviar-te de donar la teva adreça personal.<p /><b>És molt fàcil i és anònim</b>: només cal que t'inventis un nom per donar-lo allà on te'l demanin."
,"rsssubscription" => "Subscriu-te al RSS de PookMail perquè els correus t'arribin directament al teu ordinador."
,"rss.desc" => "El feed RSS de Pookmail.com et permet saber com està la safata d'entrada de qualsevol compte de PookMail."
,"request4trans" => "<b>Vols veure P<font color='red'>o</font><font color='blue'>o</font>kMail&#8482; en la teva llengua?</b> <br /><br /> Busquem traductors que vulguin donar-nos un cop de mà traduint aquest servei a d'altres idiomes. Si hi vols col·laborar, sisplau envia'ns un missatge a <b><script type='text/javascript'>document.write(foo())</script></b>."
,"visitBlog" => "Visita el Bl<font color='red'>o</font>g <font color='blue'>O</font>ficial"
 ) 
);

  $langs["ca"] = $skin_ca;
?>
