<?php
// $Id: cs.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language: Czech
// ENCODING: ISO-8859-2
// AUTHOR: shinnoki <shinnoki@seznam.cz>
//         Martin <pooklang.5.martrix@spameater.org>


$skin_cs = array( 

"label" => 
 array ( 
 "about" => "O stránce"
,"back" => "Zpìt"
,"changeLang" => "Zmìnit jazyk"
,"date" => "Datum"
,"delete" => " Smazat"
,"doclick" => "Kliknout"
,"enter" => "Vstoupit"
,"from" => "Od"
,"furtherHelp" => "Dal¹í Pomoc"
,"have" => "Máte"
,"here" => "Tady"
,"howto" => "Jak pou¾ít __PM__"
,"logout" => "Odpojit"
,"mails" => "maily"
,"message" => "zpráva"
,"please" => "Prosím"
,"save" => "Ulo¾it"
,"step" => "Krok"
,"sorry" => "Promiòte"
,"subject" => "Pøedmìt"
,"toretry" => "Opakovat"
,"viewRawmail" => "Otevøít zdroj emailu"
,"welcome" => "Vítejte"
,"welcometo" => "Vítejte v __PM__"
 ) 

, "locale" => 
 array (
  "charset" => "ISO-8859-2"
 ,"lang" => "cs"
 )

, "help" => 
 array (
 "404" => "Stránka, kterou hledáte nebyla nalezena!<p />Mo¾ná by jste mìli zaèít"
,"500" => "Ná¹ server neumìl zpracovat vá¹ po¾adavek nebo se stala jiná nespecifikovaná chyba."
,"saveMail" => "Umo¾òuje vám ulo¾it tento email, a importovat za pomoci va¹eho emailového klienta"
,"viewMail" => "Mù¾ete vidìt originál emailu"
,"deleteMail" => "Odstraòit email z tohoto systému"
 )

, "text" => 
 array ( 
 "about.feeds" => "RSS 2.0 kanály se nacházejí kdekoliv, kde uvidíte oran¾ové logo <span class='rss'>RSS 2.0</span>."
,"about.feeds.url" => "Hlavní formát RSS adresy je <b>http://www.pookmail.com/rss/emailovy_ucet.xml</b>"
,"about.feeds.aggregator" => "Zobrazte jednu z PookMail.com adres ve vasem <a href='http://interval.cz/clanek.asp?article=2050'>RSS agregátoru</a>."
,"about.feeds.aggregatorStep1" => "Zkopírovat RSS adresu úètu, který vás zajímá."
,"about.feeds.aggregatorStep2" => "Zkopírovat URL do pole pro URL adresu"
,"about.furtherHelp" => " Otázky, komentáøe, chyby atd. posílejte prosím pøímo na <b><script type='text/javascript'>document.write(foo())</script></b>."
 ,"about.visitBlog" => "Navativte <a id='blog' href='http://pookmail.blogspot.com'>Blog na PookMail.com</a> a zjistíte poslední novinky!"
,"deleteKO" => "Vá¹ email nemù¾ být smazán"
,"deleteOK" => "Vá¹ email byl smazán"
,"howtostep1" => "Místo toho, aby jste davali va¹i emailovou adresu na ka¾dou stránku na svìte, staèí kdy¾ si vymyslíte imaginární jméno na <i>@pookmail.com</i>.<br />Napøíklad: <b>neotravujtemne@pookmail.com</b>"
,"howtostep2" => "Vyèkejte dokud Vám dojde email."
,"howtostep3" => "Pøipojte se k PookMail.com vlo¾ením vymy¹leného emailového jméno (<b>neotravujtemne</b>) do prázdného okna a kliknìte na <kbd>Vstoupit</kbd>"
,"howtostep4" => "Po 24 hodinach bude email poslaný na va¹e pøístupové jméno ze systému."
,"whatispookmail" => "<b>PookMail.com</b> je system <i>jednorázové emailové schránky</i>. Pou¾ijte PookMail.com k tomu, aby jste nemuseli dávat va¹i emailovou adresu na podezøelých stránkách.<p /><b>PookMail.com</b je velmi <b>jednoduchý, anonymní a zabavný</b>! Pouze si vymyslete jméno a vstupte!"
,"rsssubscription" => "Pøedplate si RSS kanál PookMailu a získejte mo¾nost doruèení emailu pøímo na va¹í pracovní plochu!"
,"rss.desc" => "PookMail.com RSS kanál vám umo¾òuje vìdìt, kdy máte pøíchozí emaily na kterémkoliv úètu na PookMail."
,"request4trans" => "<b>Chcete vidìt P<font color='red'>o</font><font color='blue'>o</font>kMail&#8482; ve va¹em jazyce?</b> <br /><br /> Hledáme pøekladaèe, kteøí by nám pomáhali pøekládat na¹i slu¾by do dal¹ích jazykù. Pokud by jste chtìli spolupracovat, za¹lete email na <b><script type='text/javascript'>document.write(foo())</script></b>."
 ,"visitBlog" => "Navativte <font color='red'>O</font>ficiální Bl<font color='blue'>o</font>g!"
 ) 
);

  $langs["cs"] = $skin_cs;
?>
