<?php
// $Id: da.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language: Danish
// ENCODING: ISO-8859-1
// AUTHOR: Andy Monie <bordsalg@yahoo.dk>


$skin_da = array( 

"label" => 
 array ( 
  "about" => "om/info"
 ,"back" => "Tilbage"
 ,"date" => "Dato"
 ,"delete" => "Slet"
 ,"doclick" => "klik"
 ,"enter" => "LOGPÅ"
 ,"feeds" => "Feeds"
 ,"from" => "Fra"
 ,"furtherHelp" => "Mere Hjælp"
 ,"have" => "Du har"
 ,"here" => "her"
 ,"howto" => "Bruger vejledning __PM__"
 ,"logout" => "Log af"
 ,"mails" => "mails"
 ,"message" => "Besked"
 ,"please" => "Venligst"
 ,"save" => "gem"
 ,"step" => "Trin"
 ,"sorry" => "Undskyld"
 ,"subject" => "Emne"
 ,"toretry" => "prøv igen"
 ,"viewRawmail" => "Se Raw Mail"
 ,"welcome" => "Velkommen"
 ,"welcometo" => "Velkommen til __PM__"
 ) 

, "locale" => 
 array (
  "charset" => "ISO-8859-1"
  ,"lang" => "da"
 )

, "help" => 
 array (
  "404" => "Siden er ikke fundet!<p />Måske skulle du start ved."
 ,"500" => "Vores server kunne enten ikke håndtere dit forspørgsel eller var der et andet fejl."
 ,"saveMail" => "Tillader at du gemmer denne mail, for så at importere den med din favorit mail program"
 ,"viewMail" => "Du kan se den original mail i alle detaljer ( Raw )"
 ,"deleteMail" => "Fjerner mailen fra systemet"
 )

, "text" => 
 array ( 
  "about.feeds" => "RSS 2.0 feeds er tilgængelig når du ser en orange <span class='rss'>RSS 2.0</span> logo."
 ,"about.feeds.url" => "Den general format af RSS 2.0 urls er <b>http://www.pookmail.com/rss/email_account.xml</b>"
 ,"about.feeds.aggregator" => "Se en af PookMail.com feeds i din <a href='http://en.wikipedia.org/wiki/News_aggregator'>RSS Aggregator</a>"
 ,"about.feeds.aggregatorStep1" => "Kopier den adresse/genvej som korresponderer med kontoen som interesserer dig."
 ,"about.feeds.aggregatorStep2" => "Indsæt adressen i din læser."
 ,"about.furtherHelp" => "Venligst sende spørgsmål, kommentarer, fejl rapporter direkte til os på <b><script type='text/javascript'>document.write(foo())</script></b>."
 ,"deleteKO" => "Din mail kan ikke slettes"
 ,"deleteOK" => "Din mail er nu slettet"
 ,"howtostep1" => "Undgå at give din mail adresse til samtlige web sider ved brug af et imaginær adresse <i>@pookmail.com</i>.<br />For eksempel: <b>forstyrmigikke@pookmail.com</b>"
 ,"howtostep2" => "Vent på din mail."
 ,"howtostep3" => "Log på PookMail.com ved at skrive dit imaginær mail navn  (<b>forstyrmigikke</b>) i velkomst siden, og klik <kbd>LOGPÅ</kbd>"
 ,"howtostep4" => "Efter 24 timer vil mail associeret med dit login navn blive renset fra systemet."
 ,"whatispookmail" => "<b>PookMail.com</b> er et <i>brug og smid væk mail</i> system. Ved at brug PookMail kan du undgå at give din mail adresse til usikker eller ukendt modtagere.<p />Det er <b>nemt, anonymt og sjov</b>! Find bare på et navn og Kom igang!"
 ,"rsssubscription" => "Abonnere på PookMail's RSS feeds og få mails sendt direkte til dit skrivebord!"
 ,"rss.desc" => "PookMail.com RSS feed tillader dig at kende indkommende mails fra et hvilketsomhelst konto"
 ,"request4trans" => "<b>Vil du se P<font color='red'>o</font><font color='blue'>o</font>kMail&#8482; i dit eget sprog?</b> <br /><br /> Vi leder efter personer som kan hjælpe med at oversætte denne service til andre sprog. Hvis du gerne vil, send venligst en mail til <b><script type='text/javascript'>document.write(foo())</script></b>."
 ) 
);

  $langs["da"] = $skin_da;
?>
