<?php
// $Id: en_us.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language: English
// ENCODING: ISO-88591
// AUTHOR: Mike Blake <chikoon@gmail.com>


$skin_enus = array( 

"label" => 
 array ( 
  "about"   => "about" 
 ,"back"    => "Back" 
 ,"comingsoon" => "Coming Soon"
 ,"changeLang" => "Change Language"
 ,"date"    => "Date" 
 ,"delete"  => "Delete"
 ,"discard"  => "Discard"
 ,"doclick" => "click"
 ,"enter"   => "Go" 
 ,"feeds"   => "Feeds" 
 ,"four"    => "4"
 ,"from"    => "From" 
 ,"furtherHelp" => "Further Help"
 ,"have"    => "You have" 
 ,"here"    => "here" 
 ,"howto"   => "How to use __PM__" 
 ,"international"   => "international"
 ,"logout"  => "Logout" 
 ,"mails"   => "mails" 
 ,"message" => "Message" 
 ,"one"     => "1"
 ,"please"  => "Please" 
 ,"reply"   => "reply" 
 ,"reply.email" => "Reply Email" 
 ,"send.email" => "Send Email" 
 ,"save"    => "save" 
 ,"step"    => "Step" 
 ,"sorry"   => "Sorry" 
 ,"subject" => "Subject" 
 ,"toretry" => "to retry" 
 ,"three"   => "3"
 ,"two"     => "2"
 ,"viewRawmail" => "View Raw Mail" 
 ,"welcome" => "Welcome" 
 ,"welcometo" => "Welcome to __PM__" 
 )

, "locale" => 
 array (
  "charset" => "ISO-8859-1"
 ,"lang" => "en"
 )

, "help" => 
 array (
  "404" => "The page requested wan not found!<p />Perhaps you should start at"
 ,"500" => "our server didn't like your request or something was wrong."
 ,"saveMail" => "Allows you save this email, and import it with your favorite email client"
 ,"viewMail" => "You could see the original raw email"
 ,"deleteMail" => "Removes the email from the system"
 )

, "text" => 
 array ( 
  "about.feeds" => "RSS 2.0 feeds are available wherever you see an orange <span class='rss'>RSS 2.0</span> logo."
 ,"about.feeds.url" => "The general format of RSS urls is <b>http://www.pookmail.com/rss/email_account.xml</b>"
 ,"about.feeds.aggregator" => "To view one of the PookMail.com feeds in your <a href='http://en.wikipedia.org/wiki/News_aggregator'>RSS Aggregator</a>"
 ,"about.feeds.aggregatorStep1" => "Copy the URL/shortcut that corresponds to the account that interests you."
 ,"about.feeds.aggregatorStep2" => "Paste the URL into your reader."
 ,"about.furtherHelp" => "Please send questions, comments, bug reports etc directly to us at <b><script type='text/javascript'>document.write(foo())</script></b>."
 ,"about.visitBlog" => "Visit <a id='blog' href='http://pookmail.blogspot.com'>PookMail.com Blog</a> to get the last news!"
 ,"captcha" => "Type the number you see in the image"
 ,"deleteKO" => "Your email cannot be deleted"
 ,"deleteOK" => "Your email has been deleted"
 ,"dbm.subject" => "Example account"
 ,"dbm.body" => "This account is only an example. For your security we don't allow sending or reading e-mails from this account. Please try another one. <p />Thank you."
 ,"howtostep1" => "Instead of giving your real email address to every website on Earth, just make up an imaginary name for <i>@pookmail.com</i>.<br />Example: <b>dontbotherme@pookmail.com</b>"
 ,"howtostep2" => "Wait for your email to arrive."
 ,"howtostep3" => "Login to PookMail.com by typing your imaginary email name (<b>dontbotherme</b>) into the login form, and click <kbd>GO</kbd>"
 ,"howtostep4" => "After 24 hours, the email associated with your login name will be cleaned from the system."
 ,"whatispookmail" => "<b>PookMail.com</b> is a <i>disposable email account</i> system. Use PookMail.com to avoid giving your personal email address to suspicious websites.<p />It's very <b>easy, anonymous and fun</b>! Just think up a name and GO!"
 ,"rsssubscription" => "Subscribe to PookMail's RSS feeds to get emails delivered directly to your desktop!"
 ,"rss.desc" => "Pookmail.com RSS feed allows you to know the incoming emails of any PookMail account."
 ,"request4trans" => "<b>Do you want to see P<font color='red'>o</font><font color='blue'>o</font>kMail&#8482; in your own language?</b> <br /><br /> We are looking for translators who would like to help us translate this service into other languages. If you would like to collaborate, please send an email to <b><script type='text/javascript'>document.write(foo())</script></b>."
 ,"visitBlog" => "Visit <font color='red'>O</font>fficial Bl<font color='blue'>o</font>g!"
 ) 
);

  $langs["en_us"] = $skin_enus;
?>
