<?php
// $Id: es_es.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language: Spanish
// ENCODING: ISO-88591
// AUTHOR: Alex Martin <alex.martin@bostgallery.com>
   
$skin_eses = array( 

"label" => 
 array ( 
  "about"   => "acerca de" 
 ,"back"    => "Volver" 
 ,"changeLang" => "Cambiar de Idioma" 
 ,"date"    => "Fecha" 
 ,"delete"  => "Borrar" 
 ,"discard"  => "Cancelar"
 ,"doclick" => "haga click"
 ,"enter"   => "Entrar" 
 ,"from"    => "De" 
 ,"furtherHelp" => "Ayuda Adicional"
 ,"have"    => "Tiene" 
 ,"here"    => "aqu&iacute;" 
 ,"howto"   => "Como usar __PM__" 
 ,"international"  => "internacional" 
 ,"logout"  => "Salir" 
 ,"mails"   => "mails" 
 ,"message" => "Mensaje" 
 ,"please"  => "Por favor" 
 ,"reply"   => "responder" 
 ,"reply.email" => "Responder Email" 
 ,"send.email" => "Enviar Email" 
 ,"save"    => "Guardar" 
 ,"sorry"   => "Lo sentimos"
 ,"step"    => "Paso" 
 ,"subject" => "Asunto" 
 ,"toretry" => "para intentarlo de nuevo" 
 ,"viewRawmail" => "Ver Mensaje Original" 
 ,"welcome" => "Bienvenido" 
 ,"welcometo" => "Bienvenido a __PM__" 
 ) 

, "locale" => 
 array (
  "charset" => "ISO-8859-1"
 ,"lang" => "es"
 )

, "help" => 
 array (
  "404" => "¡La p&aacute;gina solicitada no existe!<p />Quiz&aacute;s deber&iacute;a ir a"
 ,"500" => "algo ha ido mal o bien hay alg&uacute;n problema con su petici&oacute;n"
 ,"saveMail" => "Permite guardar el correo, para luego importarlo con su cliente de correo"
 ,"viewMail" => "Permite ver el mail original"
 ,"deleteMail" => "Elimina este correo del sistema"
 )

, "text" => 
 array ( 
  "about.feeds" => "Los feeds RSS 2.0 estar&aacute;n siempre disponibles donde se vea el logotipo <span class='rss'>RSS 2.0</span>."
 ,"about.feeds.url" => "El formato general de la URL del RSS es <b>http://www.pookmail.com/rss/cuenta_de_correo.xml</b>"
 ,"about.feeds.aggregator" => "Para ver alguno de los feed de PookMail.com feeds en su <a href='http://en.wikipedia.org/wiki/News_aggregator'>Agregador RSS:</a>"
 ,"about.feeds.aggregatorStep1" => "Copie la URL que corresponda a la cuenta que le interesa."
 ,"about.feeds.aggregatorStep2" => "Pegue la URL en su lector de feeds."
 ,"about.furtherHelp" => "Env&iacute;enos directamente sus preguntas, comentarios, sugerencias, bugs, etc a la cuenta de correo <b><script type='text/javascript'>document.write(foo())</script></b>."
 ,"about.visitBlog" => "Visita el <a id='blog' href='http://pookmail.blogspot.com'>Blog de PookMail.com</a> para estar al tanto de las &uacute;ltimas noticias"
 ,"captcha" => "Escribe el n&uacute;mero que ves en la imagen"
 ,"deleteKO" => "No se ha podido borrar el correo"
 ,"deleteOK" => "El correo ha sido borrado"
 ,"howtostep1" => "Cuando le pidan su direcci&oacute;n de correo, inv&eacute;ntese una cualquiera que termine en <i>@pookmail.com</i>.<br /> Por ejemplo: <b>esinventada@pookmail.com</b>" 
 ,"howtostep2" => "Espere un tiempo a que el mail llegue a <b>PookMail.com</b>."
 ,"howtostep3" => "Entre en <b>PookMail.com</b> poniendo <b>esinventada</b> en el formulario, y haga click en <kbd>ENTRAR</kbd>"
 ,"howtostep4" => "El mail recibido será eliminado, autom&aacute;ticamente por el sistema, despu&eacute;s de 24 horas."
 ,"whatispookmail" => "<b>PookMail.com</b> es un sistema de cuentas de correo de <i>usar-y-tirar</i>, que se puede utilizar para evitar tener que dar su cuenta de correo personal.<p />Es muy <b>f&aacute;cil de usar</b>: inv&eacute;ntese una cuenta y d&eacute;sela a la persona o web que le pida una cuenta de correo."
			     ,"rsssubscription" => "¡Suscr&iacute;base al RSS de PookMail para que los emails le lleguen directamente a su PC!"
 ,"rss.desc" => "El sistema RSS de Pookmail.com le permite monitorizar los emails que lleguen a una cuenta de correo de Pookmail."
 ,"request4trans" => "<b>&iquest;Quiere ver P<font color='red'>o</font><font color='blue'>o</font>kMail&#8482; en su idioma?</b> <br /><br /> Estamos buscando traductores que nos ayuden en la traducci&oacute;n de este servicio a otros idiomas. Si desea ayudarnos, p&oacute;ngase en contacto con nosotros enviando un mail a <b><script type='text/javascript'>document.write(foo())</script></b>."
 ,"visitBlog" => "&iexcl;Visita el Bl<font color='red'>o</font>g <font color='blue'>O</font>ficial!"
 ) 
);

  $langs["es_es"] = $skin_eses;
?>
