<?php
// $Id: et.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language: Estonian
// ENCODING: ISO-8859-4
// AUTHOR: Tanel Liiv <kuratkull@koffer.ee>


$skin_et = array( 

"label" => 
 array ( 
  "about" => "sellest"
 ,"back" => "Tagasi"
 ,"changeLang" => "Vaheta Keelt"
 ,"date" => "Kuupäev"
 ,"delete" => "Kustuta"
 ,"doclick" => "kliki"
 ,"enter" => "Mine!"
 ,"feeds" => "Feeds"
 ,"four" => "4"
 ,"from" => "Kust"
 ,"furtherHelp" => "Edasine Abi"
 ,"have" => "Sinul on"
 ,"here" => "siin"
 ,"howto" => "Kuidas kasutada __PM__"
 ,"logout" => "Logi välja"
 ,"mails" => "kirjad"
 ,"message" => "Teade"
 ,"one" => "1"
 ,"please" => "Palun"
 ,"save" => "salvesta"
 ,"step" => "Samm"
 ,"sorry" => "Vabandust"
 ,"subject" => "Pealkiri"
 ,"three" => "3"
 ,"toretry" => "uuesti proovida"
 ,"two" => "2"
 ,"viewRawmail" => "töötlemata kiri"
 ,"welcome" => "Teretulemast"
 ,"welcometo" => "Teretulemast __PM__"
 )

, "locale" => 
 array (
  "charset" => "ISO-8859-4"
 ,"lang" => "et"
 )

, "help" => 
 array (
  "404" => "Lehekülge ei leitud!<p />Ehk peaks sa alustama"
 ,"500" => "meie serverile ei meeldinud su toiming või oli midagi valesti"
 ,"saveMail" => "Lubab sul salvestada seda kirja, ja importida seda sinu e-maili programmiga"
 ,"viewMail" => "Sa saad näha algset töötlemata kirja"
 ,"deleteMail" => "Eemaldab kirja süsteemist"
 )

, "text" => 
 array ( 
  "about.feeds" => "RSS 2.0 feeds'id on saadaval kui sa näed oranzi <span class='rss'>RSS 2.0</span> logo."
 ,"about.feeds.url" => "Tavaline RSS urlide formaat on <b>http://www.pookmail.com/rss/email_account.xml</b>"
 ,"about.feeds.aggregator" => "Vaata mõnda PookMail.com feeds'i oma RSS <a href='http://en.wikipedia.org/wiki/News_aggregator'>Aggregatoris</a>"
 ,"about.feeds.aggregatorStep1" => "Kopeeri URL/otsetee mis käib sind huvita konto kohta."
 ,"about.feeds.aggregatorStep2" => "Kleebi URL oma RSS lugejasse."
 ,"about.furtherHelp" => "Palun saada küsimused, kommentaarid, vea teated jms. otse meile, kasutades -> <b><script type='text/javascript'>document.write(foo())</script></b>."
 ,"deleteKO" => "Sinu kirja ei saa kustutada"
 ,"deleteOK" => "Sinu kiri kustutati"
 ,"howtostep1" => "Selle asemel et anda oma päris e-maili aadress iagle leheküljele, mõtle lihtsalt välja nimi <i>@pookmail.com</i>.<br />Example: <b>ärasegamind@pookmail.com</b>"
 ,"howtostep2" => "Oota kuni su kiri tuleb."
 ,"howtostep3" => "Logi sisse PookMail.com trükkides sisse oma väljamõeldud nime (<b>ärasegamind</b>) login kasti, ja vajuta <kbd>Mine</kbd>"
 ,"howtostep4" => "Peale 24a tundi, e-mail seostatud sinu aadressiga saab automaatselt kustutatud."
 ,"whatispookmail" => "<b>PookMail.com</b> on <i>ühekordse kasutusega e-maili aadressi</i> süsteem. Kasuta PookMail.com et hoiduda andmast oma päris e-maili kahtlastele lehtedele.<p />See on väga <b>lihtne, anonüümne ja lõbus</b>! Lihtsalt mõtle välja nimi ja Mine!"
 ,"rsssubscription" => "Pane kirja PookMail'i RSS feedsile et saada kirja otse desktopile!"
 ,"rss.desc" => "Pookmail.com RSS feed'sid lubavad sul vaadata kirju mis ilmuvad ükskõik millisele kontole."
 ,"request4trans" => "<b>Kas sa tahad näha P<font color='red'>o</font><font color='blue'>o</font>kMail&#8482; enda keeles?</b> <br /><br /> Me otsime tõlkijaid kes aitaksid tõlkida seda süsteemi teistesse keeltesse. Kui sooviksid aidata, saada kiri <b><script type='text/javascript'>document.write(foo())</script></b>."
 ) 
);

  $langs["et"] = $skin_et;
?>
