<?php
// $Id: fa.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language: Farsi
// ENCODING: UTF-8
// AUTHOR: Eric <bright.email@gmail.com>


$skin_fa = array( 

"label" => 
 array ( 
  "about" => "درباره"
 ,"back" => "عقب"
 ,"changeLanguage" => "تغییر زبان"
 ,"date" => "تاریخ"
 ,"delete" => "حذف"
 ,"doclick" => "کلیک"
 ,"enter" => "برو!"
 ,"feeds" => "Feeds"
 ,"four" => "چهارم"
 ,"from" => "از"
 ,"furtherHelp" => "کمک ِ بیشتر"
 ,"have" => "شما"
 ,"here" => "اینجا"
 ,"howto" => "چگونگی استفاده از __PM__"
 ,"international" => "بین المللی"
 ,"logout" => "خروج"
 ,"mails" => "نامه دارید"
 ,"message" => "پیام"
 ,"one" => "اول"
 ,"please" => "لطفا"
 ,"save" => "ذخیره"
 ,"step" => "قدم"
 ,"sorry" => "متاسفم"
 ,"subject" => "موضوع"
 ,"three" => "سوم"
 ,"toretry" => "تلاش ِ مجدد"
 ,"two" => "دوم"
 ,"viewRawmail" => "مشاهده ی کد ایمیل"
 ,"welcome" => "خوش آمدید"
 ,"welcometo" => "به __PM__ خوش آمدید"
 )

, "locale" => 
 array (
  "charset" => "UTF-8"
 ,"lang" => "fa"
 ,"direction" => "rtl"
 ) 
, "help" => 
 array (
  "404" => "صفحه ای که خواستید پیدا نشد!<p />شاید باید از اینجا شروع کنید"
 ,"500" => "یا چیزی اشتباه شده و یا سرور ما درخواست شما را نپسندید."
 ,"saveMail" => "به شما اجازه می دهد که این ایمیل را ذخیره کرده یا وارد ِ برنامه ی مدیریتِ ایمیلتان کنید."
 ,"viewMail" => "می توانید کد های خام ایمیل ِ اصلی را ببینید"
 ,"deleteMail" => "ایمیل را از سیتم پاک می کند"
 )

, "text" => 
 array ( 
  "about.feeds" => "هر جایی که لوگوی نارنجی ِ <span class='rss'>RSS 2.0</span> را مشاهده می کنید RSS feed مهیا است."
 ,"about.feeds.url" => "فرمت عمومی ِ آدرس RSS این است: <b>http://www.pookmail.com/rss/email_account.xml</b>"
 ,"about.feeds.aggregator" => "برای مشاهده ی یکی از feed های Pookmail.com در برنامه ی <a href='http://en.wikipedia.org/wiki/News_aggregator'>RSS Aggregator</a>"
 ,"about.feeds.aggregatorStep1" => "آدرس URL feed جایی را که مورد علاقه تان است کپی کنید."
 ,"about.feeds.aggregatorStep2" => "آدرس URL را در برنامه ی اخبار-خوانتان Paste کنید."
 ,"about.furtherHelp" => "لطفا درخواست ها، ایرادات، باگ یا موضوعات دیگر را مستقیما به این آدرس بفرستید <b><script type='text/javascript'>document.write(foo())</script></b>"
 ,"deleteKO" => "ایمیلتان قابل پاک کردن نیست"
 ,"deleteOK" => "ایمیلتان پاک شده است"
 ,"howtostep1" => "بجای دادن آدرس ایمیل واقعی تان به همه ی وبسایتهای دنیا، کافیست یک نام دلبخواه ِ خیالی را&nbsp;با پسوند ِ pookmail.com@ انتخاب کنید.<br />مثال: <b>dontbotherme@pookmail.com</b>"
 ,"howtostep2" => "منتظر شوید تا ایمیلتان برسد."
 ,"howtostep3" => "وارد کردن ایمیل خیالیتان در فرم ورود (dontbotherme) و کلیک کردن دکمه ی&laquo;برو!&raquo; وارد PookMail.com بشوید."
 ,"howtostep4" => "پس از 24 ساعت، ایمیل ِمربوط به نام ِ ورودی تان از روی سیستم پاک خواهد شد."
 ,"whatispookmail" => "<b>PookMail.com</b> این یک سیستم ایمیل یکبار مصرفست. برای احتراز از دادن ایمیل شخصی تان به وبسایتهای نامطمئن از PookMail.com استفاده کنید.<p />این کار بسیار <b>ساده، ناشناس، و جالب</b> است! کافیست که یک نام انتخاب کنید و بروید!"
 ,"rsssubscription" => "مشترک RSS feed های PookMail.com شوید تا ایمیل ها رامستقیما روی دسکتاپتان تحویل بگیرید!"
// ,"rsssubscription" => "!شوید تا ایمیل ها رامستقیما روی دسکتاپتان تحویل"
// ,"rsssubscription" => "!شوید تا ایمیل ها رامستقیما روی دسکتاپتان تحویل بگیرید&nbsp; PookMail.com های RSS feed مشترک"
 ,"rss.desc" => "Pookmail.com RSS feed allows you to know the incoming emails of any PookMail account."
 ,"request4trans" => "<b>آیا دوست دارید که &trade;</b><b>P<font color='red'>o</font><font color='blue'>o</font>kMail</b> <b>رابه زبان خودتان ببینید؟</b><br /><br />ما به دنبال مترجمانی هستیم که مایل باشند ما را در ترجمه ی این سرویس به زبان های دیگر یاری دهند. اگردوست دارید کمک کنید لطفا ایمیلی به این آدرس بزنید: <b><script type='text/javascript'>document.write(foo())</script></b>."
 )
);

  $langs["fa"] = $skin_fa;
?>
