<?php
// $Id: fr.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language: French
// ENCODING: ISO-8859-1 
// AUTHOR: Bruno <bdanna@gmail.com>


$skin_fr = array( 

"label" => 
 array ( 
  "about" => "A propos de"
 ,"back" => "Retour"
 ,"changeLang" => "Changer de langue"
 ,"date" => "Date"
 ,"delete" => "Supprimer"
 ,"doclick" => "cliquez"
 ,"enter" => "Entrer"
 ,"feeds" => "Flux"
 ,"four" => "4"
 ,"from" => "De"
 ,"furtherHelp" => "Plus d'aide"
 ,"have" => "Vous avez"
 ,"here" => "ici"
 ,"howto" => "Comment utiliser __PM__"
 ,"logout" => "Déconnexion"
 ,"mails" => "messages"
 ,"message" => "Message"
 ,"one" => "1"
 ,"please" => "S'il vous plait"
 ,"save" => "sauver"
 ,"step" => "Etape"
 ,"sorry" => "Désolé"
 ,"subject" => "Sujet"
 ,"three" => "3"
 ,"toretry" => "pour ré-éssayer"
 ,"two" => "2"
 ,"viewRawmail" => "Voir le code source du message"
 ,"welcome" => "Bienvenue"
 ,"welcometo" => "Bienvenue à __PM__"
 )

, "locale" => 
 array (
  "charset" => "ISO-8859-1"
 ,"lang" => "fr"
 )

, "help" => 
 array (
  "404" => "La page demandée n'a pas été trouvée!<p />Vous devriez peut-être commencer par"
 ,"500" => "notre serveur ne comprend pas votre requête ou quelque chose est erroné."
 ,"saveMail" => "Permet de sauvegarder ce message, et de l'importer dans votre client de messagerie préféré"
 ,"viewMail" => "Vous pouvez voir le code source du message original"
 ,"deleteMail" => "Supprime le message de votre système"
 )

, "text" => 
 array ( 
  "about.feeds" => "Les flux RSS 2.0 sont disponibles chaque fois que vous voyez un logo orange <span class='rss'>RSS 2.0</span>."
 ,"about.feeds.url" => "Le format général d'une URL au format RSS est <b>http://www.pookmail.com/rss/email.xml</b>"
 ,"about.feeds.aggregator" => "Pour voir un des flux RSS de PookMail.com dans votre <a href='http://en.wikipedia.org/wiki/News_aggregator'>aggrégateur RSS</a>" 
 ,"about.feeds.aggregatorStep1" => "Copier l'URL/raccourcis qui correspond au compte qui vous intéresse."
 ,"about.feeds.aggregatorStep2" => "Collez l'URL dans votre lecteur."
 ,"about.furtherHelp" => "Envoyez nous vos questions, commentaires, problèmes etc à <b><script type='text/javascript'>document.write(foo())</script></b>."
 ,"deleteKO" => "Votre message ne peut être supprimé"
 ,"deleteOK" => "Votre message a été supprimé"
 ,"howtostep1" => "Plutôt que de donner votre véritable adresse de messagerie à chaque site de la terre, utilisez simplement un nom imaginaire suivi de <i>@pookmail.com</i>.<br />Exemple: <b>nomauhasard@pookmail.com</b>"
 ,"howtostep2" => "Attendez que votre message arrive."
 ,"howtostep3" => "Connectez-vous à PookMail.com en utilisant votre nom imaginaire (<b>nomauhasard</b>) dans le formulaire d'identification, et cliquez sur <kbd>Entrer</kbd>"
 ,"howtostep4" => "Après 24 heures, le message associé à votre identifiant sera automatiquement effacé du système."
 ,"whatispookmail" => "<b>PookMail.com</b> est un système de <i>compte eMail jetable</i>. Utilisez PookMail.com pour éviter de donner votre adresse mail personnelle à des sites douteux.<p />C'est très <b>simple, anonyme et plaisant</b>! Imaginez simplement un nom et allez-y!"
 ,"rsssubscription" => "Utilisez les flux RSS de PookMail pour recevoir directement vos messages!"
 ,"rss.desc" => "Le flux RSS de Pookmail.com vous permet de connaître les nouveaux messages de n'importe quel compte PookMail."
 ,"request4trans" => "<b>Voulez-vous voir P<font color='red'>o</font><font color='blue'>o</font>kMail&#8482; dans votre propre langue?</b> <br /><br /> Nous recherchons des traducteurs qui aimeraient nous aider à traduire ce service dans d'autres langues. Si vous êtes intéressé, envoyez-nous un mail à <b><script type='text/javascript'>document.write(foo())</script></b>."
 ) 
);

  $langs["fr"] = $skin_fr;
?>
