<?php
// $Id: ge.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// LANGUAGE: German
// ENCODING: ISO-8859-1
// AUTHOR: Rolf "anon" <brinkkrol@gmx.de>
// REVISED BY: Michael H. <mail@mhankemann.net>


$skin_ge = array( 

"label" => 
 array ( 
  "about" => "Über __PM__"
 ,"back" => "Zurück"
 ,"changeLang" => "Sprache wechseln"
 ,"date" => "Datum"
 ,"delete" => "löschen"
 ,"doclick" => "klick"
 ,"enter" => "Go"
 ,"feeds" => "Feeds"
 ,"from" => "von"
 ,"furtherHelp" => "Weitere Hilfe"
 ,"have" => "du hast"
 ,"here" => "hier"
 ,"howto" => "Wie kannst du __PM__ nutzen"
 ,"logout" => "Logout"
 ,"mails" => "mail(s)"
 ,"message" => "Meldung"
 ,"please" => "Bitte"
 ,"save" => "speichern"
 ,"step" => "Schritt"
 ,"sorry" => "Sorry"
 ,"subject" => "Betreff"
 ,"toretry" => "noch einmal versuchen (simply: nochmal)" 
 ,"viewRawmail" => "ohne Formatierung ansehen"
 ,"welcome" => "Willkommen"
 ,"welcometo" => "Willkommen bei __PM__"
 )

, "locale" => 
 array (
  "charset" => "ISO-8859-1"
 ,"lang" => "ge"
 )

, "help" => 
 array (
  "404" => "Die angeforderte Seite wurde nicht gefunden!<p />Evtl. solltest du beginnen bei."
 ,"500" => "Unser Server mochte deine Anfrage nicht oder etwas war falsch."
 ,"saveMail" => "erlaubt dir, diese eMail zu speichern und sie in dein bevorzugtes eMail-Programm zu importieren"
 ,"viewMail" => "du konntest die originale Roh-eMail sehen"
 ,"deleteMail" => "entfernt die eMail vom System"
 )

, "text" => 
 array ( 
  "about.feeds" => "RSS 2.0 Feeds sind überall verfügbar, wo du ein orangefarbenes <span class='rss'>RSS 2.0</span> Logo sehen kannst."
 ,"about.feeds.url" => "Das generelle Format von RSS-URLs ist <b>http://www.pookmail.com/rss/email_account.xml</b>"
 ,"about.feeds.aggregator" => "Betrachte eine der PookMail.com Feeds in deinem <a href='http://en.wikipedia.org/wiki/News_aggregator'>RSS Aggregator</a>"
 ,"about.feeds.aggregatorStep1" => "Kopiere die URL/Tastenkürzel der zu dem Account passt."
 ,"about.feeds.aggregatorStep2" => "Füge die URL in deinen Reader ein."
 ,"about.furtherHelp" => "Bitte sende Fragen, Kommentare, Fehlermeldungen usw. direkt an uns <b><script type='text/javascript'>document.write(foo())</script></b>."
 ,"deleteKO" => "Deine email kann nicht gelöscht werden"
 ,"deleteOK" => "Deine email wurde gelöscht"
 ,"howtostep1" => "Anstatt deine richtige eMail-Adresse jeder Website auf der Welt zu offenbaren, erfinde lieber einen imaginären Namen bei <i>@pookmail.com</i>.<br />Beispiel: <b>dontbotherme@pookmail.com</b>"
 ,"howtostep2" => "Warte darauf, daß deine eMail ankommt."
 ,"howtostep3" => "Logge dich bei PookMail.com ein, indem du deinen imaginären eMail Namen (<b>dontbotherme</b>) in das Login-Formular eintippst, und auf <kbd>GO</kbd> klickst"
 ,"howtostep4" => "Nach 24 Stunden wird deine mit deinem gewählten Login-Namen erzeugte eMail-Adresse vom System entfernt."
 ,"whatispookmail" => "<b>PookMail.com</b> ist ein <i>Wegwerf-eMail-Konto</i> System. Nutze PookMail.com um zu vermeiden, dass deine persönliche eMail-Adresse in nicht vertrauenswürdigen Websites angezeigt wird.<p />Es ist sehr <b>leicht, anonym und spa&szlig;ig</b>! Denk dir einfach einen Namem aus und klicke GO!"
 ,"rsssubscription" => "Bestelle PookMail's RSS Feeds, um deine eMails direkt auf deinen desktop geliefert zu bekommen!"
 ,"rss.desc" => "Pookmail.com RSS Feed informiert dich über den Empfang jeder eMail, die dein PookMail-Konto erreicht."
 ,"request4trans" => "<b>Möchtest du P<font color='red'>o</font><font color='blue'>o</font>kMail&#8482; in deiner eigenen Sprache?</b> <br /><br /> Wir suchen Übersetzer, die uns gern helfen möchten, diesen Service in andere Sprachen zu übersetzen. Wenn du mit uns zusammenarbeiten möchtest, sende bitte eine eMail an <b><script type='text/javascript'>document.write(foo())</script></b>."
 ) 
);

  $langs["ge"] = $skin_ge;
?>
