<?php
// $Id: gl.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language: Galician
// ENCODING: ISO-88591
// AUTHOR: Diego Iglesias <iglesias.diego@hotmail.com>


$skin_gl = array( 

"label" => 
 array ( 
 "about" => "Acerca de"
,"back" => "Voltar"
,"comingsoon" => "Pronto dispoñible"
,"changeLang" => "Mudar lingua"
,"date" => "Data"
,"delete" => "Eliminar"
,"doclick" => "clique"
,"enter" => "Entrar"
,"feeds" => "Feeds"
,"four" => "4"
,"from" => "Dende"
,"furtherHelp" => "Máis axuda"
,"have" => "Ten"
,"here" => "aquí"
,"howto" => "Como usar __PM__"
,"international" => "internacional"
,"logout" => "Saír"
,"mails" => "mensaxe(s)"
,"message" => "Mensaxe"
,"one" => "1"
,"please" => "Por favor"
,"save" => "Gardar"
,"step" => "Paso"
,"sorry" => "Desculpe"
,"subject" => "Tema"
,"three" => "3"
,"toretry" => "Para volver tentar"
,"two" => "2"
,"viewRawmail" => "Ver Mail"
,"welcome" => "Benvido, "
,"welcometo" => "Benvido a __PM__"
 )

, "locale" => 
 array (
  "charset" => "ISO-8859-1"
 ,"lang" => "gl"
 )

, "help" => 
 array (
 "404" => "A páxina solicitada non foi achada!<p />Talvez debería probar en"
,"500" => "o noso servidor non aceptou a súa solicitude ou algo foi mal."
,"saveMail" => "Permítelle gardar este email e importalo co seu cliente de correo favorito"
,"viewMail" => "Pode ver o email orixinal"
,"deleteMail" => "Exclúe o email do seu sistema"
 )

, "text" => 
 array ( 
 "about.feeds" => "Os feeds RSS 2.0 estarán dispoñibles onde vexa un logo laranxa de <span class='rss'>RSS 2.0</span>."
,"about.feeds.url" => "O formato xeral das urls de RSS é <b>http://www.pookmail.com/rss/email_account.xml</b>"
,"about.feeds.aggregator" => "Vexa un dos feeds de PookMail.com no seu Agregador RSS"
,"about.feeds.aggregatorStep1" => "Copie o vínculo/URL que corresponda á conta que lle interesa."
,"about.feeds.aggregatorStep2" => "Pegue a URL no seu lector de feeds."
,"about.furtherHelp" => "Por favor, envíenos preguntas, comentarios ou informes de erros directamente a <b><script type='text/javascript'>document.write(foo())</script></b>."
,"about.visitBlog" => "Visite <a id='blog' href='http://pookmail.blogspot.com'>PookMail.com Blog</a> para coñecer as últimas noticias!"
,"deleteKO" => "O seu email non pode ser eliminado"
,"deleteOK" => "O seu email foi eliminado"
,"dbm.subject" => "Conta de exemplo"
,"dbm.body" => "Esta conta só é un exemplo. Pola súa seguridade non permitimos "
,"enviar ou ler e-mails dende esta conta. Por favor, probe con outra. <p />Grazas."
,"howtostep1" => "Se non quere divulgar o seu enderezo de correo en calquera sitio na internet, só ten que pensar un nome para <i>@pookmail.com</i>.<br />Exemplo: <b>brincadeira@pookmail.com</b>"
,"howtostep2" => "Agarde pola chegada do seu email."
,"howtostep3" => "Entre en PookMail.com escribindo o seu enderezo de email inventado (<b>brincadeira</b>) na caixa de usuario e clique en <kbd>ENTRAR</kbd>"
,"howtostep4" => "Despois de 24 horas, o seu email inventado será totalmente eliminado do sistema."
,"whatispookmail" => "<b>PookMail.com</b> é un sistema de <i>conta de correo rexeitable</i>. Use PookMail.com para evitar mostrar o seu enderezo de correo persoal aos sitios sospeitosos.<p />É moi <b>sinxelo, anónimo e divertido</b>! Pense nada máis que un nome e LISTO!"
,"rsssubscription" => "Subscríbase ao RSS de PookMail para que os emails cheguen directamente ao seu PC"
,"rss.desc" => "O sistema RSS de Pookmail.com permítelle coñecer os emails chegados a unha conta de PookMail."
,"request4trans" => "<b>Quere ver o P<font color='red'>o</font><font color='blue'>o</font>kMail&#8482; na súa propia lingua?</b> <br /><br /> Estamos a procurar persoas que queiran axudarnos a traducir este servizo a outras linguas. Se quere colaborar, envíe un email a <b><script type='text/javascript'>document.write(foo())</script></b>."
,"visitBlog" => "Visite o Bl<font color='red'>o</font>g <font color='blue'>O</font>ficial!"
 ) 
);

  $langs["gl"] = $skin_gl;
?>
