<?php
// $Id: he.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language: Hebrew
// ENCODING: UTF-8
// AUTHOR: Liron Newman <plastish@ultinet.org>
// AUTHOR: Ben Lavi <benlavi83@gmail.com>


$skin_he = array( 

"label" => 
 array ( 
  "about" => "אודות"
 ,"back" => "חזרה"
 ,"comingsoon" => "בקרוב"
 ,"changeLang" => "שינוי שפה"
 ,"date" => "תאריך"
 ,"delete" => "מחיקה"
 ,"doclick" => "לחץ"
 ,"enter" => "קדימה!"
 ,"feeds" => "ערוצים"
 ,"four" => "רביעי"
 ,"from" => "מאת"
 ,"furtherHelp" => "עזרה נוספת"
 ,"have" => "יש לך"
 ,"here" => "כאן"
 ,"howto" => "הוראות שימוש"
 ,"international" => "בין לאומי"
 ,"logout" => "יציאה מהחשבון"
 ,"mails" => " הודעות"
 ,"message" => "הודעה"
 ,"one" => "ראשון"
 ,"please" => "בבקשה"
 ,"save" => "שמור"
 ,"step" => "צעד"
 ,"sorry" => "סליחה"
 ,"subject" => "נושא"
 ,"three" => "שלישי"
 ,"toretry" => "כדי לנסות שנית"
 ,"two" => "שני"
 ,"viewRawmail" => "הצג את קוד המקור של ההודעה"
 ,"welcome" => "ברוכים הבאים,"
 ,"welcometo" => "ברוכים הבאים אל <b>P<font color='red'>o</font><font color='blue'>o</font>kMail.com</b>"
 )

, "locale" => 
 array (
  "charset" => "UTF-8"
 ,"lang" => "he"
 ,"direction" => "rtl"
 )

, "help" => 
 array (
  "404" => "הדף המבוקש לא נמצא!<p />מומלץ להתחיל ב:"
 ,"500" => "השרת שלנו דחה את בקשתך,או שקיימת בעיה אחרת."
 ,"saveMail" => "מאפשר לך לשמור הודעה זו, ולייבא אותה לתוכנת הדוא\"ל החביבה עליך"
 ,"viewMail" => "מאפשר לך לצפות בקובץ המקור של ההודעה"
 ,"deleteMail" => "מוחק הודעה זו מהחשבון"
 )

, "text" => 
 array ( 
  "about.feeds" => "ערוצי RSS 2.0 זמינים בדפים בהם מוצג הלוגו הכתום <span class='rss'>RSS 2.0</span>."
 ,"about.feeds.url" => "הפורמט הכללי של כתובות ה-RSS הינו <b>http://www.pookmail.com/rss/email_account.xml</b>"
 ,"about.feeds.aggregator" => " על מנת לצפות באחד הערוצים של PookMail.com באמצעות תוכנת קריאת ה-RSS שלך"
 ,"about.feeds.aggregatorStep1" => "העתק את קיצור הדרך/ה-URL המתאים עבור החשבון שמעניין אותך."
 ,"about.feeds.aggregatorStep2" => "הדבק את הנ\"ל לתוך תוכנת הקריאה שלך."
 ,"about.furtherHelp" => "נא דווחו על בעיות, שאלות, הערות, הארות  וכיו\"ב ישירות אלינו, לכתובת <b><script type='text/javascript'>document.write(foo())</script></b>."
 ,"about.visitBlog" => "בקרו ב<a id='blog' href='http://pookmail.blogspot.com'>בלוג של PookMail.com</a> על מנת להתעדכן בכל החדשות !"
 ,"deleteKO" => "לא ניתן למחוק את ההודעה שלך"
 ,"deleteOK" => "ההודעה שלך נמחקה"
 ,"dbm.subject" => "חשבון לדוגמא"
 ,"dbm.body" => "חשבון זה הינו לצרכי הדגמה בלבד. משיקולי אבטחה שונים, איננו מאפשרים משלוח או קריאת הודעות מחשבון זה. אנא נסה חשבון אחר.  <p />תודה."
 ,"howtostep1" => "במקום למסור את כתובת הדואר האלקטרוני האמיתית שלך לכל אתר בעולם, המצא כתובת דמיונית עבור <i dir='ltr'>@pookmail.com</i>.<br />לדוגמא: <b>dontbotherme@pookmail.com</b>"
 ,"howtostep2" => "המתן עד שההודעה שנשלחה אליך תגיע."
 ,"howtostep3" => "התחבר אל PookMail.com על ידי רישום הכתובת הדמיונית שלך (<b>dontbotherme</b>) בתיבת הכניסה, ולחץ <kbd> קדימה! </kbd>"
 ,"howtostep4" => "לאחר 24 שעות, הדואר שנשלח לכתובת שאיתה נכנסת ימחק מהמערכת."
 ,"whatispookmail" => "האתר <b>PookMail.com</b> הינו מערכת <u>חשבונות דואר אלקטרוני לשימוש חד פעמי</u>. השתמש ב-PookMail.com והמנע מלמסור את כתובתך הפרטית לאתרים חשודים.<p />זה  <b>קל, אנונימי, וכיף</b>! רק חשוב על שם ו<b>קדימה!</b>"
 ,"rsssubscription" => "הרשם לערוצי ה-RSS של PookMail ותוכל לקבל הודעות ישירות לשולחן העבודה שלך!"
 ,"rss.desc" => "ערוצי ה-RSS של Pookmail.com מאפשרים לך לדעת על הודעות שהגיעו לכל חשבון PookMail ."
 ,"request4trans" => "<b>האם אתה רוצה לראות את P<font color='red'>o</font><font color='blue'>o</font>kMail&#8482; בשפה שלך?</b> <br /><br /> אנחנו מחפשים אנשים המעוניינים לסייע לנו לתרגם שירות זה לשפות אחרות. אם ברצונך לסייע, אנא שלח הודעה אל <b><script type='text/javascript'>document.write(foo())</script></b>."
 ,"visitBlog" => "בקרו ב<font color='red'>ב</font>לוג הר<font color='blue'>ש</font>מי!"
 )
);

  $langs["he"] = $skin_he;
?>
