<?php
// $Id: hu.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language: Hungarian
// ENCODING: UTF-8
// AUTHOR: Trifonov Andras <andras.trifonov@idom.hu> 


$skin_hu = array(

"label" =>
 array (
  "about" => "Névjegy"
 ,"back" => "Vissza"
 ,"changeLang" => "Másik nyelv"
 ,"date" => "Dátum"
 ,"delete" => "Törlés"
 ,"doclick" => "click"
 ,"enter" => "Tovább"
 ,"feeds" => "RSS feeds"
 ,"four" => "4"
 ,"from" => "Feladó"
 ,"furtherHelp" => "További infó"
 ,"have" => ""
 ,"here" => "itt"
 ,"howto" => "Használat útmutató __PM__"
 ,"logout" => "Kilépés"
 ,"mails" => "leveled érkezett"
 ,"message" => "Üzenet"
 ,"one" => "1"
 ,"please" => "Kérem"
 ,"save" => "mentés"
 ,"step" => "Lépés"
 ,"sorry" => "Bocsi"
 ,"subject" => "Tárgy"
 ,"three" => "3"
 ,"toretry" => "újra"
 ,"two" => "2"
 ,"viewRawmail" => "Formázatlan  levél"
 ,"welcome" => "Üdvözlünk"
 ,"welcometo" => "Üdvözöl a __PM__"
 )

, "locale" =>  
 array (
  "charset" => "UTF-8"
 ,"lang" => "hu"
 )

, "help" =>
 array (
  "404" => "A kért oldal nem található!<p />Próbáld esetleg itt"
 ,"500" => "A szerverünknek nem tetszett a kérésed, vagy valami hiba történt"
 ,"saveMail" => "Elmentheted a levelet és beimportálhatod a saját leveleződbe."
 ,"viewMail" => "Megnézheted a levelet úgy, ahogy érkezett, formázás nélkül."
 ,"deleteMail" => "Törli a levelet a rendszerből"
 )

 , "text" =>
  array (
  "about.feeds" => "Az RSS 2.0 feeds szolgáltatás elérhető mindenhol, ahol a narancs szímű <span class='rss'>RSS 2.0</span> logót látod."
 ,"about.feeds.url" => "Az RSS URL-ek általános formája <b>http://www.pookmail.com/rss/email_account.xml</b>"
 ,"about.feeds.aggregator" => "Böngéssz PookMail.com RSS feed-eket a saját <a href='http://en.wikipedia.org/wiki/News_aggregator'>RSS Aggregatoroddal</a>"
 ,"about.feeds.aggregatorStep1" => "Másold ki a megfelelő fiókhoz tartozó az URL-t/linket"
 ,"about.feeds.aggregatorStep2" => "Illeszd be az URL-t a böngésződbe."
 ,"about.furtherHelp" => "Ha kérdésed, észrevételed van, esetleg hibát találtál, küldd el közvetlenül nekünk a <b><script type='text/javascript'>document.write(foo())</script></b> címre."
 ,"deleteKO" => "A levelet nem tudtuk törölni"
 ,"deleteOK" => "A levelet töröltük"
 ,"howtostep1" => "Tartsd titokban a valódi e-mail címed! Találj ki egy nevet a <i>@pookmail.com</i> elejére.<br />Példa: <b>ne_zavarj@pookmail.com</b>"
 ,"howtostep2" => "Várj, amíg megérkezik a leveled."
 ,"howtostep3" => "Írd be a PookMail.com-ra a kitalált nevet (<b>ne_zavarj</b>) a bejelentkező képernyőn és kattints a <kbd>Tovább</kbd> gombra."
 ,"howtostep4" => "24 óra múlva a kitalált nevedre érkezett levelek törlődnek a rendszerből."
 ,"whatispookmail" => "A <b>PookMail.com</b> egy <i>eldobható e-mail postafiók</i> rendszer. A PookMail.com használatával nem kell  személyes e-mail címedet megadni a gyanús oldalakon.<p />Tökéletesen <b>egyszerű, névtelen és vicces</b>! Csak találj ki egy nevet és hajrá!"
 ,"rsssubscription" => "A PookMail RSS feeds szolgáltatásával a leveleid közvetlenül a saját gépedre érkezhetnek!"
 ,"rss.desc" => "A Pookmail.com RSS feeds szolgáltatással értesítést kaphatsz bármilyen PookMail postafiókba érkező levélről."
 ,"request4trans" => "<b>Beszéljen a P<font color='red'>o</font><font color='blue'>o</font>kMail&#8482; a saját nyelveden?</b> <br /><br /> Fordítókat keresünk, aki segítenek nekünk átültetni ezt a szolgáltatást más nyelvekre. Ha kedvet érzel hozzá, küldj egy levelet a <b><script type='text/javascript'>document.write(foo())</script></b> címre."
  )
 );

   $langs["hu"] = $skin_hu;
 ?>
