<?php
// $Id: id.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language: Indonesian
// ENCODING: ISO-8859-1
// AUTHOR: Eriko Adjie <nasigoreng@gmail.com>


$skin_id = array( 

"label" => 
 array ( 
  "about" => "Tentang"
 ,"back" => "Kembali"
 ,"changeLang" => "Ganti Bahasa"
 ,"Date" => "Tanggal"
 ,"delete" => "Hapus"
 ,"doclick" => "Klik"
 ,"enter" => "Lanjutkan!"
 ,"feeds" => "Feeds"
 ,"four" => "4"
 ,"from" => "Dari"
 ,"furtherHelp" => "Bantuan Lebih Lanjut"
 ,"have" => "Anda Punya"
 ,"here" => "Di Sini"
 ,"howto" => "Bagaimana untuk menggunakan __PM__"
 ,"logout" => "Logout"
 ,"mails" => "mails"
 ,"message" => "Pesan"
 ,"one" => "1"
 ,"please" => "Harap"
 ,"save" => "Simpan"
 ,"step" => "Langkah"
 ,"sorry" => "Maaf"
 ,"subject" => "Subject"
 ,"three" => "3"
 ,"toretry" => "Untuk Mengulangi"
 ,"two" => "2"
 ,"viewRawmail" => "Lihat Raw Mail"
 ,"welcome" => "Selamat Datang"
 ,"welcometo" => "Selamat Datang Di __PM__"
 )

, "locale" => 
 array (
  "charset" => "ISO-8859-1"
 ,"lang" => "id"
 )

, "help" => 
 array (
  "404" => "Halaman yang diminta tidak ditemukan!<p />Sebaiknya anda start dari"
 ,"500" => "Server kami tidak menyukai permintaan anda atau ada sesuatau yang salah."
 ,"saveMail" => "Anda dapat menyimpan email ini, dan mengimportnya dengan email client favorit anda"
 ,"viewMail" => "Anda dapat melihat raw email"
 ,"deleteMail" => "Menghapus email dari system"
 )

, "text" => 
 array ( 
  "about.feeds" => "RSS 2.0 feeds tersedia bila anda melihat logo <span class='rss'>RSS 2.0</span> berwarna orange."
 ,"about.feeds.url" => "Format umum dari RSS urls adalah <b>http://www.pookmail.com/rss/email_account.xml</b>"
 ,"about.feeds.aggregator" => " melihat salah satu PookMail.com feeds dalam <a href='http://en.wikipedia.org/wiki/News_aggregator'>RSS Aggregator</a> anda."
 ,"about.feeds.aggregatorStep1" => "Copy URL/shortcut yang berhubungan dengan account yang anda suka."
 ,"about.feeds.aggregatorStep2" => "Paste URL ke reader anda."
 ,"about.furtherHelp" => "Harap kirim pertanyaan, komentar, laporan kesalahan dll langsung kepada kami ke <b><script type='text/javascript'>document.write(foo())</script></b>."
 ,"deleteKO" => "Email anda tidak dapat dihapus"
 ,"deleteOK" => "Email anda telah terhapus"
 ,"howtostep1" => "Daripada memberikan alamat email anda yang asli ke semua website di dunia, buat saja nama samaran untuk <i>@pookmail.com</i>.<br />Example: <b>dontbotherme@pookmail.com</b>"
 ,"howtostep2" => "Tunggu sampai email anda datang."
 ,"howtostep3" => "Login ke PookMail.com dengan mengetik nama email samaran anda (<b>dontbotherme</b>) ke formulir login , dan klik <kbd>GO</kbd>"
 ,"howtostep4" => "Setelah 24 Jam, email yang anda buat akan dihapus dari system."
 ,"whatispookmail" => "<b>PookMail.com</b> adalah sebuah system <i>email account sekali pakai</i> . Gunakan PookMail.com untuk menghindar dari memberi alamat email pribadi anda ke website yang mencurigakan.<p />Sangat <b>mudah, anonymous dan fun</b>! Anda cukup memikirkan satu nama samaran dan Go!"
 ,"rsssubscription" => "Subscribe ke PookMail's RSS feeds sehingga email terkirim langsung ke desktop anda!"
 ,"rss.desc" => "Pookmail.com RSS feed mengijinkan anda untuk mengetahui email yang datang dari account PookMail manapun."
 ,"request4trans" => "<b>Do you want to see P<font color='red'>o</font><font color='blue'>o</font>kMail&#8482; in your own language?</b> <br /><br /> We are looking for translators who would like to help us transtalating this service to others languages. If you like to collaborate, please send an email to <b><script type='text/javascript'>document.write(foo())</script></b>."
 ) 
);

  $langs["id"] = $skin_id;
?>
