<?php
// $Id: it.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language: Italian
// ENCODING: ISO-88591
// AUTHOR: Giuseppe Guarnieri <beppegg@email.it>

$skin_it = array(

"label" => 
 array ( 
  "about" => "Informazioni su"
 ,"back" => "Indietro"
 ,"date" => "Data"
 ,"delete" => "Cancella"
 ,"doclick" => "click"
 ,"enter" => "Vai"
 ,"feeds" => "Feeds"
 ,"from" => "Da"
 ,"furtherHelp" => "Ulteriore aiuto"
 ,"have" => "Hai"
 ,"here" => "qui"
 ,"howto" => "Come usare __PM__"
 ,"logout" => "Esci"
 ,"mails" => "messaggi"
 ,"message" => "Messaggio"
 ,"please" => "Per favore"
 ,"save" => "salva"
 ,"step" => "Passo"
 ,"sorry" => "Spiacenti"
 ,"subject" => "Soggetto"
 ,"toretry" => "per riprovare"
 ,"viewRawmail" => "Visualizza messaggio grezzo"
 ,"welcome" => "Benvenuto"
 ,"welcometo" => "Benvenuto su __PM__"
 ) 

, "locale" => 
 array (
  "charset" => "ISO-8859-1"
 ,"lang" => "it"
 )

, "help" => 
 array (
  "404" => "La pagina che hai richiesto non &egrave; disponibile!<p />Forse dovresti partire da"
 ,"500" => "Il nostro server non ha apprezzato la tua richiesta o qualcosa &egrave; andata storta."
 ,"saveMail" => "Ti permette di salvare questo messaggio ed importarlo nel tuo programma di posta preferito"
 ,"viewMail" => "Puoi vedere il messaggio di posta grezzo originale"
 ,"deleteMail" => "Rimuove il messaggio dal sistema"
 )
		     
, "text" => 
 array ( 
  "about.feeds" => "i feed RSS 2.0 sono disponibili ogni qual volta vedi un logo arancione <span class='rss'>RSS 2.0</span>."
 ,"about.feeds.url" => "Il formato generico degli URL RSS &egrave; <b>http://www.pookmail.com/rss/email_account.xml</b>"
 ,"about.feeds.aggregator" => "Visualizza uno dei feed PookMail.com nel tuo <a href='http://en.wikipedia.org/wiki/News_aggregator'>Aggregator RSS</a>"
 ,"about.feeds.aggregatorStep1" => "Copia l'URL/collegamento che corrisponde all'account che ti interessa."
 ,"about.feeds.aggregatorStep2" => "Incolla l'URL nel tuo programma di lettura."
 ,"about.furtherHelp" => "Si prega di inviare domande, commenti, rapporti di errori etc direttamente a noi a <b><script type='text/javascript'>document.write(foo())</script></b>."
 ,"deleteKO" => "Il tuo messaggio non pu&ograve; essere cancellato"
 ,"deleteOK" => "Il tuo messaggio &egrave; stato cancellato"
 ,"howtostep1" => "Al posto di fornire il tuo indirizzo email reale ad ogni sito web sulla faccia della terra, inventati semplicemente un nome immaginario per <i>@pookmail.com</i>.<br />Esempio: <b>nonscocciare@pookmail.com</b>"
 ,"howtostep2" => "Attendi che il messaggio di posta elettronica ti arrivi."
 ,"howtostep3" => "Accedi a PookMail.com inserendo il nome inventato (<b>nonscocciare</b>) nel form di Login, e clicca <kbd>Vai</kbd>"
 ,"howtostep4" => "Dopo 24 ore, il messaggio associato al tuo nome di accesso sar&agrave; cancellato dal sistema."
 ,"whatispookmail" => "<b>PookMail.com</b> &egrave; un sistema di <i>indirizzi email usa-e-getta</i>. Utilizza PookMail.com per evitare di fornire il tuo indirizzo email personale a siti web sospetti.<p />&Egrave; estremamente <b>facile, anonimo e divertente</b>! Pensa semplicemente ad un nome e VAI!"
 ,"rsssubscription" => "Sottoscrivi il feed RSS di PookMail per avere i messaggi di posta direttamente sul tuo desktop!"
 ,"rss.desc" => "il feed RSS di Pookmail.com ti permette di conoscere i messaggi in arrivo di qualsiasi account PookMail."
 ,"request4trans" => "<b>Vorresti avere P<font color='red'>o</font><font color='blue'>o</font>kMail&#8482; nella tua lingua?</b> <br /><br /> Cerchiamo traduttori che vorrebbero aiutarci a tradurre questo servizio in altre lingue. Se vuoi collaborare, per favore invia un'e-mail a <b><script type='text/javascript'>document.write(foo())</script></b>."
 ) 
);

  $langs["it"] = $skin_it;
?>
