<?php
// $Id: ja.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language: Japanese
// ENCODING: UTF-8
// AUTHOR: Shoyz Blah <admin@shoyz.com>


$skin_ja = array(

"label" =>
 array (
 "about" => "について"
,"availableIn" => "__PM__  は  利用できるで... また"
,"back" => " 背部"
,"comingsoon" => "すぐに来ること"
,"changeLang" => "変更の言語"
,"date" => "日付"
,"delete" => "削除"
,"doclick" => "かちりと言う音"
,"enter" => "行きなさい!"
,"feeds" => "供給"
,"four" => "4"
,"from" => "から"
,"furtherHelp" => "それ以上の助け"
,"have" => "あなたは持っている"
,"here" => "ここに"
,"howto" => "__PM__ の を使用する方法"
,"international" => "国際"
,"logout" => "ログアウト"
,"mails" => "郵便"
,"message" => "メッセージ"
,"one" => "1"
,"please" => "Please"
,"save" => "を除けば"
,"step" => "ステップ"
,"sorry" => "残念"
,"subject" => "主題"
,"thanksTranslators" => "訳者のおかげで特別な"
,"three" => "3"
,"toretry" => "to retry"
,"two" => "2"
,"viewRawmail" => "眺めの未加工郵便"
,"welcome" => "歓迎"
,"welcometo" => "__PM__ の への歓迎"
)
, "locale" => 
 array (  
  "charset" => "UTF-8" 
 ,"lang" => "ja" 
 )

, "help" => array (
 "404" => "ページはwan のない 多分あなたべ きであるで始まる要求した"
,"500" => "あなたののような私達のサーバー は要 求または何か間違っていた。"
,"saveMail" => "この電子メールを除けばあなたを許可し, あ なたの好みの電子メールの顧客とのそれを輸入する"
,"viewMail" => "あなたは元の未加工電子メールを見ることが できる"
,"deleteMail" => "システムから電子メールを取除く"
 )

, "text" =>
 array (
 "about.feeds" => "あなたがオレンジRSS_2.0 ロゴを見ると ころはどこでもRSS 2.0 の供給は利用できる。"
,"about.feeds.url" => "RSS のurls の一般的なフォーマットは<b>http://www.pookmail.com/rss/email_account.xml</b>"
,"about.feeds.aggregator" => "である PookMail.com の眺め1 はあな たのRSS Aggregator"
,"about.feeds.aggregatorStep1" => "を入れる Copy URL/shortcut 記述に対応する興味あなた。"
,"about.feeds.aggregatorStep2" => "あなたの読者にurl 貼りなさい。"
,"about.furtherHelp" => "<b><script type='text/javascript'>document.write(foo())</script></b> で私達へ質問, コメント, 虫のレポート等を直接送りなさ い。"
,"about.visitBlog" => "訪問<a id='blog' href='http://pookmail.blogspot.com'>PookMail.com Blog</a>  最後のニュースを得るため!"
,"deleteKO" => "あなたの電子メ ールは削除された"
,"deleteOK" => "であることができない  あなたの電子 メールはbeed 削除された"
,"dbm.subject" => "を持っている 例の記述"
,"dbm.body" => "この記述は唯一に例である。あなたの保証のために私 達はdon't この記述から電子メールを送るか, または読むこ とを割り当てる。もう1<p /> あなたに感謝しな さい。"
,"howtostep1" => "地球のあらゆるwebsite にあなたの実質のeメ ールアドレスを与えるかわりに, ちょうど <i>@pookmail.com</i>.<br /> 例のための想像名前を構成しな さい:  <b>dontbotherme@pookmail.com</b>"
,"howtostep2" => "着く あなたの電子メールのための待ち時間"
,"howtostep3" => "ログオン形態 へのあなたの想像電子メールの名前(<b>dontbotherme) の タイプによるPookMail.com へのログオン, とかちりと言う音 <kbd>GO</kbd> "
,"howtostep4" => "24 時間後に, あなたのログオン名 前と関連付けられた電子メールはシステムから取除かれる。"
,"whatispookmail" => "<b>PookMail.com</b> は<i>disposable 電 子メールaccount</i> システムである。疑ったwebsites.<b>easy, 匿名It's 非常に< とfun</b>!  ちょうど名前の上で考え, 行きなさい!"
,"rsssubscription" => "電子 メールを直接あなたの卓上に渡されて得るために PookMail's RSS の供給へ予約購読しなさい !"
,"rss.desc" => "Pookmail.com RSS の供給はあなたがPookMail のど の記述の入って来る電子メールでも知ることを可能にする。"
,"request4trans" => "<b> あなたが P<font color='red'>o</font><font color='blue'>o</font>kMail&#8482; を見たいDo;  あ なた自身でlanguage?</b><br /><br /> 私達訳者を捜し ている言語他へこのサービスをtranstalating 私達を助けること を望む。あなたが協力するのを好んだら<b><script  type='text/javascript'>document.write(foo())</script></b> へ電子メールを送りなさい喜ぶために。"
,"visitBlog" => " 訪問 <font color='red'>O</font>fficial Bl<font color='blue'>o</font>g!"
 )
);

  $langs["ja"] = $skin_ja;
?>