<?php
// $Id: lb.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language: Luxemburgish [lb]
// ENCODING: UTF-8
// AUTHOR: Fred Feuerstein <glukkebuppert@hotmail.com>
   
$skin_lb = array( 

"label" => 
 array ( 
 "about" => "Iwert"
,"back" => "Zereck"
,"comingsoon" => "Kennt geschwenn"
,"changeLang" => "Aaner Sproch"
,"date" => "Datum"
,"delete" => "Löschen"
,"doclick" => "Klick"
,"enter" => "An lass!"
,"feeds" => "Feeds"
,"four" => "veier"
,"from" => "Vun"
,"furtherHelp" => "Weider Hellef"
,"have" => "Du hues"
,"here" => "hei"
,"howto" => "Wei et funktioneiert __PM__"
,"international" => "International"
,"logout" => "Ausloggen"
,"mails" => "E-Mailen"
,"message" => "Noriichten"
,"one" => "eng"
,"please" => "w.e.g."
,"save" => "Spaicheren"
,"step" => "Schrett"
,"sorry" => "Pardon"
,"subject" => "Betreff"
,"three" => "drai"
,"toretry" => "nach eemol versichen"
,"two" => "zwee"
,"viewRawmail" => "E-Mail Source kucken"
,"welcome" => "Welkomm"
,"welcometo" => "Welkomm zu __PM__"
 ) 

, "locale" => 
 array (
  "charset" => "UTF-8"
 ,"lang" => "lu"
 )

, "help" => 
 array (
 "404" => "Dei Sait wousste ugefroot hues gouf net fonnt <p />Vielleicht sollste et bei nach eng Keier versichen"
,"500" => "Eisen Server huet deng Ufroo net gär oder eppes waar falsch"
,"saveMail" => "Erlaabt der et deng Mail ze saven, an mat dengem Mail-Programm opzemaan"
,"viewMail" => "Du kanns den E-Mail Source kucken"
,"deleteMail" => "Löscht d E-Mail vum System"
 )

, "text" => 
 array ( 
 "about.feeds" => "RSS 2.0 feeds sin iwerall ze hun wou den <span class='rss'>RSS 2.0</span>. logo ass"
,"about.feeds.url" => "De generellen URL ass "
,"<b>http://www.pookmail.com/rss/email_account.xml</b>"
,"about.feeds.aggregator" => " kuck een vun den RSS feeds an dengem RSS Programm"
,"about.feeds.aggregatorStep1" => "Kopeier d URL vir deen Account wou dech intresseiert"
,"about.feeds.aggregatorStep2" => "Kliew d URl an dein RSS Programm"
,"about.furtherHelp" => "Schreif deng Froen, Kommentarer an Bugs wousste fonnt hues un eis<b><script type='text/javascript'>document.write(foo())</script></b>."
,"about.visitBlog" => "Besich <a id='blog' href='http://pookmail.blogspot.com'>PookMail.com Blog</a> vir dei neitsten News"
,"deleteKO" => "E-Mail kann net gelöscht gin"
,"deleteOK" => "Deng E-Mail gouff gelöscht"
,"dbm.subject" => "Beispill-Account"
,"dbm.body" => "Desen Account ass just een Beispill. Vir är Secherheet erlaaben mer et net E-Mailen heidrop ze empfänken. W.e.g. benotzt een aaneren Account. <p /> Merci."
,"howtostep1" => "Amplaatz op all I-NET seit deng eegen E-Mail Adress ze benotzen, erfann een imaginären Numm fir <i>@pookmail.com</i>.<br />Example: <b>dontbotherme@pookmail.com</b>"
,"howtostep2" => "Waart drop dat deng E-Mail ukennt."
,"howtostep3" => "Logg dech op PookMail.com an mat dengem erfonntenen Numm (<b>dontbotherme</b>) an klick <kbd>An lass!</kbd>"
,"howtostep4" => "No 24 Stonnen get all E-Mail gelöscht dei ennert dengem erfonntenen Numm um System gespeichert ass."
,"whatispookmail" => "<b>PookMail.com</b> ass een <i>Wegwerf E-Mail Account</i> System. Benotz PookMail.com vir dat net all Beppo deng rischtesch E-Mail gewuer get.<p />Et ass wierklech <b>einfach, anonym an mecht o na Spass</b>! Numm ausdenken an lass et geet!"
,"rsssubscription" => "Ennerschreiw beim PookMail RSS Feed an du kriss deng Mailen direkt op den Desktop geliwert!"
,"rss.desc" => "PookMail.com RSS Feeds erlaaben der et emmer direkt matzekreien wannste eng E-Mail kriss."
,"request4trans" => "<b>Giffste gär P<font color='red'>o</font><font color='blue'>o</font>kMail&#8482; an denger eegener Sprooch gesin?</b> <br /><br /> Mir sichen stänneg no leit dei eis hellefen wellen desen Service an aaner Sproochen ze iwersetzen. Wann der hellefen wellt scheckt eng E-mail un <b><script type='text/javascript'>document.write(foo())</script></b>."
,"visitBlog" => "Besicht eisen <font color='red'>O</font>ffiziellen Bl<font color='blue'>o</font>g!"
 ) 
);

  $langs["lb"] = $skin_lb;
?>
