<?php
// $Id: lv.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language: Latvian
// ENCODING: UTF-8
// AUTHOR: Martins Saulitis <martins.saulitis@venta.lv>


$skin_lv = array( 

"label" => 
 array ( 
 "about" => "Par"
,"back" => "Atpakaļ"
,"comingsoon" => "Drīz būs pieejams arī"
,"changeLang" => "Mainīt valodu"
,"date" => "Datums"
,"delete" => "Dzēst"
,"doclick" => "Spiest šeit"
,"enter" => "Ienākt"
,"feeds" => "Barotnes"
,"four" => "Ceturtais solis"
,"from" => "No"
,"furtherHelp" => "Papildus informācija"
,"have" => "Jums ir"
,"here" => "šeit"
,"howto" => "Lietošanas pamācība"
,"international" => "starptautisks"
,"logout" => "Izžurnalizēties"
,"mails" => "ziņas"
,"message" => "E-pasts"
,"one" => "Pirmais solis"
,"please" => "Lūdzu"
,"save" => "saglabāt"
,"step" => ""
,"sorry" => "Atvainojet"
,"subject" => "Tēma"
,"three" => "Trešais solis"
,"toretry" => "mēģināt vēlreiz"
,"two" => "Otrais solis"
,"viewRawmail" => "apskatīt epasta detaļas"
,"welcome" => "Laipni lūdzam"
,"welcometo" => "Laipni lūdzam"
 )

, "locale" => 
 array (
  "charset" => "UTF-8"
 ,"lang" => "lv"
 )

, "help" => 
 array (
 "404" => "Meklētā lapa nav atrasta!<p />Varbūt jums vajadzētu sākt"
,"500" => "mūsu serveris neatpazina Jūsu pieprasījumu, vai arī ir radusies kļūda"
,"saveMail" => "Saglabāt šo e-pastu un pēc tam atvērt ar savu e-pasta klientu"
,"viewMail" => "Apskatīt e-pasta detaļas"
,"deleteMail" => "Izdzēst e-pastu no sistēmas"
 )

, "text" => 
 array ( 
 "about.feeds" => "RSS 2.0 barotnes ir pieejamas visur, kur jūs redzat oranžu <span class='rss'>RSS 2.0</span> logo."
,"about.feeds.url" => "RSS barotņu satura formāts ir pieejams šeit <b>http://www.pookmail.com/rss/email_account.xml</b>"
,"about.feeds.aggregator" => "Lai apskatītu jebkuru no PookMail.com barotnēm ar savu RSS apkopotāju"
,"about.feeds.aggregatorStep1" => "Nokopējiet Jūs interesējoša konta URL/īsceļu."
,"about.feeds.aggregatorStep2" => "Ievietojiet URL/īsceļu Jūsu RSS apkopotājā."
,"about.furtherHelp" => "Lūdzu sūtiet jautājumus, komentārus, kļudu ziņojumus u.c. mums <b><script type='text/javascript'>document.write(foo())</script></b>."
,"about.visitBlog" => "Apmeklējiet <a id='blog' href='http://pookmail.blogspot.com'>PookMail.com Blog</a> lai uzzinātu jaunāko informāciju!"
,"deleteKO" => "Nevar izdzēst jūsu e-pastu"
,"deleteOK" => "Jūsu e-pasts ir izdzēsts"
,"dbm.subject" => "Piemēra konts"
,"dbm.body" => "Šis konts ir kā piemērs. Drošības dēļ mēs neļaujam sūtīt, saņemt vai lasīt e-pastus no šī konta.<p />Paldies."
,"howtostep1" => "Lai nebūtu jāuzrāda save e-pasta adrese visās interneta lappusēs, uzrādiet pagaidu e-pasta adresi <i>@pookmail.com</i>.<br />Piemēram: <b>netraucet@pookmail.com</b>"
,"howtostep2" => "Sagaidiet savu e-pastu."
,"howtostep3" => "Iežurnalizējieties PookMail.com ierakstot savu izdomāto lietotājvārdu (<b>netraucet</b>) formā un spiediet <kbd>Ienākt</kbd>"
,"howtostep4" => "Pēc 24 stundām e-pasti, kuri ir saistīti ar Jūsu izdomāto lietotājvārdu tiek automātiski izdzēsti no sistēmas."
,"whatispookmail" => "<b>PookMail.com</b> ir sistēma, kura <i>automātiski</i> dzēš Jūsu nevajadzīgos e-pastus. Lietojiet PookMail.com, lai izvairītos no savas e-pasta adreses uzrādīšanas aizdomīgās tīmekļa vietnēs.<p />Tas ir ļoti <b>vienkārši un anonīmi</b>!"
,"rsssubscription" => "Parakstieties uz PookMail RSS barotnēm lai saņemtu e-pastus tieši savā apkopotājā!"
,"rss.desc" => "Pookmail.com RSS barotnes ļauj Jums uzzināt par ienākušajiem e-pastiem jebkurā no Jūsu PookMail kontiem."
,"request4trans" => "<b>Vai vēlies redzēt P<font color='red'>o</font><font color='blue'>o</font>kMail&#8482; savā valodā?</b> <br /><br /> Mēs meklējam tulkotājus, kuri spētu pārtulkot šo servisu citās valodās. Ja Jūs vēlaties piedalīties, lūdzu sūtiet e-pastu uz <b><script type='text/javascript'>document.write(foo())</script></b>."
,"visitBlog" => "Apmeklē <font color='red'>O</font>fficiālo tīmekļa žurn<font color='blue'>ā</font>lu!"
 ) 
);

  $langs["lv"] = $skin_lv;
?>
