<?php
// $Id: nl.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language:  Dutch
// ENCODING: ISO-8859-1
// AUTHOR: Vitaly Samoylik <vitaly@vitaly.org.ua>


$skin_nl = array( 

"label" => 
 array ( 
  "about" => "over __PM__"
 ,"back" => "Terug"
 ,"comingsoon" => "Binnenkort ook"
 ,"changeLang" => "Wijzig taal"
 ,"date" => "Datum"
 ,"delete" => "verwijder"
 ,"doclick" => "klik"
 ,"enter" => "Ga!"
 ,"feeds" => "Feeds"
 ,"from" => "Van"
 ,"furtherHelp" => "Overige Vragen"
 ,"have" => "Je hebt"
 ,"here" => "hier"
 ,"howto" => "Hoe gebruik je __PM__"
 ,"logout" => "Uitloggen"
 ,"mails" => "emails"
 ,"message" => "Bericht"
 ,"please" => "Alsjeblieft"
 ,"save" => "opslaan"
 ,"step" => "Stap"
 ,"sorry" => "Sorry"
 ,"subject" => "Onderwerp"
 ,"toretry" => "opnieuw proberen"
 ,"viewRawmail" => "Bekijk Raw Email"
 ,"welcome" => "Welkom"
 ,"welcometo" => "Welkom bij __PM__"
 )

, "locale" => 
 array (
  "charset" => "ISO-8859-1"
 ,"lang" => "nl"
 )

, "help" => 
 array (
  "404" => "De gezochte pagina is niet gevonden! Misschien zou je moeten beginnen op"
 ,"500" => "Onze server was niet blij met je verzoek of er ging iets mis."
 ,"saveMail" => "Hiermee kun je deze email opslaan en importeren met je favoriete email programma"
 ,"viewMail" => "Je kunt hier de originele Raw Email bekijken"
 ,"deleteMail" => "verwijder email van het systeem"
 )

, "text" => 
 array ( 
  "about.feeds" => "RSS 2.0 feeds zijn overal beschikbaar waar je het oranje <span class='rss'>RSS 2.0</span> logo ziet."
 ,"about.feeds.url" => "Over het algemeen ziet een RSS urls er zo uit <b>http://www.pookmail.com/rss/email.xml</b>"
 ,"about.feeds.aggregator" => "Bekijk de PookMail.com feeds in een <a href='http://en.wikipedia.org/wiki/News_aggregator'>RSS Feed Reader</a>"
 ,"about.feeds.aggregatorStep1" => "Kopieer de url/snelkoppeling van de account waar je interesse naar uitgaat."
 ,"about.feeds.aggregatorStep2" => "Plak de URL in je reader."
 ,"about.furtherHelp" => "Stuur svp vragen, commentaren, bugs etc direct naar ons op <b><script type='text/javascript'>document.write(foo())</script></b>."
 ,"deleteKO" => "Je email kan niet verwijderd worden"
 ,"deleteOK" => "Je email is verwijderd"
 ,"howtostep1" => "In plaats van dat je je echte email adres geeft aan elke website op aarde, verzin je gewoon een denkbeeldige naam op <i>@pookmail.com</i>.<br /> Bij voorbeeld: <b>laatmemetrust@pookmail.com</b>"
 ,"howtostep2" => "Wacht tot je email aangekomen is."
 ,"howtostep3" => "Login op PookMail.com met je verzonnen email naam (laatmemetrust) en klik <kbd>GA!</kbd>"
 ,"howtostep4" => "Na 24 uur wordt de email die bijhoort bij je verzonnen email adres verwijderd van het systeem."
 ,"whatispookmail" => "<b>PookMail.com</b> is een <i>wegwerp email account</i> systeem. Gebruik PookMail.com om te voorkomen dat je je persoonlijke email adres op onbetrouwbare websites achterlaat.<p />Het is erg <b>makkelijk, anoniem en leuk</b>! Bedenk gewoon een naam en GAAN!"
 ,"rsssubscription" => "Schrijf je in voor PookMail's RSS feeds om emails direct op je bureaublad te ontvangen!"
 ,"rss.desc" => "Met Pookmail.com RSS feed kun je inkomende emails van elk pookmail account zien."
 ,"request4trans" => "<b>Wil je P<font color='red'>o</font><font color='blue'>o</font>kMail&#8482; in je eigen taal zien?</b> <br /><br /> We zoeken altijd mensen die ons willen helpen deze service in andere talen te vertalen. Als je hieraan wilt bijdragen, stuur dan een email naar <b><script type='text/javascript'>document.write(foo())</script></b>."
 ) 
);

  $langs["nl"] = $skin_nl;
?>
