<?php
// $Id: no.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language: Norwegian
// ENCODING: ISO-8859-1
// AUTHOR: Magnus <tmfaureng@gmail.com>


$skin_no = array( 

"label" => 
 array ( 
  "about" => "om"
 ,"back" => "Tilbake"
 ,"date" => "Dato"
 ,"delete" => "Slett"
 ,"doclick" => "klikk"
 ,"enter" => "Sjekk mail!"
 ,"feeds" => "Feeds"
 ,"from" => "Fra"
 ,"furtherHelp" => "Mer hjelp"
 ,"have" => "Du har"
 ,"here" => "her"
 ,"howto" => "Slik bruker du __PM__"
 ,"logout" => "Logg ut"
 ,"mails" => "meldinger"
 ,"message" => "Melding"
 ,"please" => "Vennligst"
 ,"save" => "lagre"
 ,"step" => "Steg"
 ,"sorry" => "Beklager"
 ,"subject" => "Emne"
 ,"toretry" => "å prøve igjen"
 ,"viewRawmail" => "Vis meldingskilde"
 ,"welcome" => "Velkommen,"
 ,"welcometo" => "Velkommen til __PM__"
 )

, "locale" => 
 array (
  "charset" => "ISO-8859-1"
 ,"lang" => "no"
 )

, "help" => 
 array (
  "404" => "Siden du ser etter finnes ikke.<p />Prøv å start fra"
 ,"500" => "Serveren vår likte ikke forespørselen din (eller det oppstod en annen feil)"
 ,"saveMail" => "Lar deg lagre denne meldingen, slik at du kan importere den til en annen e-postklient"
 ,"viewMail" => "Viser e-posten og meldingshodet i klartekst"
 ,"deleteMail" => "Sletter meldingen fra systemet"
 )

, "text" => 
 array ( 
  "about.feeds" => "RSS 2.0-feeds er tilgjengelig overalt hvor du ser en <span class='rss'>RSS 2.0</span> logo."
 ,"about.feeds.url" => "Det generelle formatet på RSS-adresser er <b>http://www.pookmail.com/rss/epost_konto.xml</b>"
 ,"about.feeds.aggregator" => " vis PookMail.com-feeds i en <a href='http://en.wikipedia.org/wiki/News_aggregator'>RSS-leser</a>"
 ,"about.feeds.aggregatorStep1" => "Kopier adressen/snarveien til kontoen du er interessert i."
 ,"about.feeds.aggregatorStep2" => "Lim inn adressen i RSS-leseren."
 ,"about.furtherHelp" => "Spørsmål, kommentarer, feilrapporter osv. kan sendes direkte til oss på <b><script type='text/javascript'>document.write(foo())</script></b> (henvendelser kun på engelsk)."
 ,"deleteKO" => "Meldingen kan ikke slettes"
 ,"deleteOK" => "Meldingen har blitt slettet"
 ,"howtostep1" => "Istedenfor å oppgi din virkelige e-postadresse til &quot;Gud og Hvermann&quot; finner du bare på en adresse som ender med <i>@pookmail.com</i>.<br />Eksempel: <b>leiavreklame@pookmail.com</b>"
 ,"howtostep2" => "Vent på at noen skal sende deg e-post."
 ,"howtostep3" => "Logg inn på PookMail.com ved å fylle inn navnet på din fiktive e-postadresse (<b>leiavreklame</b>) i feltet til høyre, og klikk <kbd>Sjekk mail!</kbd>"
 ,"howtostep4" => "E-post sendt til PookMail-adresser er tilgjengelige i 24 timer, og blir deretter slettet fra systemet."
 ,"whatispookmail" => "<b>PookMail.com</b> er en tjeneste som tilbyr gratis <i>bruk-og-kast e-postkontoer</i>. Ved å bruke PookMail.com slipper du å oppgi din personlige e-postadresse til potensielt useriøse nettsteder.<p />Det er <b>enkelt, anonymt og gøy</b>! Bare finn på et navn og klikk &quot;Sjekk mail!&quot;"
 ,"rsssubscription" => "Abonnér på PookMails RSS-feeds, og få e-post levert direkte på skrivebordet!"
 ,"rss.desc" => "PookMail.com RSS-feed lar deg sjekke innkommende mail i en hvilken som helst PookMail-konto."
 ,"request4trans" => "<b>Vil du se P<font color='red'>o</font><font color='blue'>o</font>kMail&#8482; på ditt eget språk?</b> <br /><br /> Vi ser etter oversettere som kan hjelpe oss å oversette denne tjenesten til andre språk. Hvis du er interessert, vennligst send en e-post til <b><script type='text/javascript'>document.write(foo())</script></b>."
 ) 
);

  $langs["no"] = $skin_no;
?>
