<?php
// $Id: pa.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language: Punjabi
// ENCODING: ISO-88591
// AUTHOR: Powerdyne <powerdyne@gmail.com>
   
$skin_pa = array( 

"label" => 
 array ( 
 "about" => "Assi Kaun Haan"
,"back" => "Pichhe"
,"changeLang" => "Boli Badlo"
,"date" => "Miti"
,"delete" => "Hata do"
,"doclick" => "Click"
,"enter" => "Chalo!"
,"feeds" => "Feeds"
,"four" => "4"
,"from" => "Kitho"
,"furtherHelp" => "Hor Madad Vaste"
,"have" => "Tusi"
,"here" => "Ithe"
,"howto" => "Kiddan Karange __PM__"
,"logout" => "Logout"
,"mails" => "Mails"
,"message" => "Sneha"
,"one" => "1"
,"please" => "Kirpa Karke"
,"save" => "Bachao (Save)"
,"step" => ""
,"sorry" => "Maafi Deyo"
,"subject" => "Vishye"
,"three" => "3"
,"toretry" => "Dubara Koshish Karo"
,"two" => "2"
,"viewRawmail" => "Raw Mail Vekho"
,"welcome" => "Ji Aayian Nu"
,"welcometo" => "Ji Aayian Nu __PM__"
 ) 

, "locale" => 
 array (
  "charset" => "ISO-8859-1"
 ,"lang" => "pa"
 )

, "help" => 
 array (
 "404" => "Eh page eithe nahi hai. Tusi itho Shuruat Karo"
,"500" => "Request vich koi galti hai."
,"saveMail" => "Mail aapne computer de mail client vich pa sakde ho"
,"viewMail" => "Raw email Vekho"
,"deleteMail" => "Email nu hata do"
 )

, "text" => 
 array ( 
 "about.feeds" => "RSS 2.0 feeds maujud hai, jad vi tusi kesari rang vala RSS_2.0 logo dekho ge."
,"."
,"about.feeds.url" => "RSS urls da likhan da dhang eh hai - <b>http://www.pookmail.com/rss/email_account.xml</b>"
,"about.feeds.aggregator" => " PookMail.com feeds de feeds tusi apne RSS Aggregator de khate vich dekh sakde ho."
,"about.feeds.aggregatorStep1" => "Us URL ya shortcut de nakal utaro jehri tuhanu vaidya lagdi hai."
,"about.feeds.aggregatorStep2" => "URL nu apne reader ch bhar deyo."
,"about.furtherHelp" => "Kirpa karke aapniya shikayatan, sawal sanu bejo <b><script type='text/javascript'>document.write(foo())</script></b>."
 ,"dbm.subject" => "Example account"
 ,"dbm.body" => "Eh khata sirf check karan waste hai. Es khate toon email behjna te lena allowed nahi hai. Kirpa karke kuch hor try karo.<p />Shukriya."
,"deleteKO" => "Eh Mail Delete nahi ho sakdi"
,"deleteOK" => "Mail Delete ho gaye hai"
,"howtostep1" => "Appne asli email id di than te tusi ek jali email address de sakde ho, jidan  <i>@pookmail.com</i>.<br />Example: <b>dontbotherme@pookmail.com</b>"
,"howtostep2" => "Aapne mail nu udeeko."
,"howtostep3" => "PookMail.com de khate vich login karan vaste apana jali email name (<b>dontbotherme</b>) login form de vich likho, te click <kbd>GO</kbd>"
,"howtostep4" => "Ek din, matlab 24 ghateyan vich tuhade khate choon sariyan mailan delete ho jaan giyaan."
,"whatispookmail" => "<b>PookMail.com</b> ek <i>Jali email account</i> banaun di than hai. Pookmail.com ton tusi hun appna asli email address dite bina he mail mangwa sakde ho, koi ve website ton ja phir kisi vi email address toon<p />Eh hun bahut <b>assan te majedar</b> hai! Hun ik nawa naam socho te cholo!"
,"rsssubscription" => "PookMail diyan RSS feeds vich shamil ho ke, emails sidda aapne computer de desktop te lavo."
,"rss.desc" => "Pookmail.com RSS feed toon tusi kise vi PookMail account diyan mails dekh sake ho."
,"request4trans" => "<b>Tusi P<font color='red'>o</font><font color='blue'>o</font>kMail&#8482; de punjabi translation nu vadiya kar sakde ho?</b> <br /><br /> aapniyan socha kirpa karke sanu mail karo <b><script type='text/javascript'>document.write(foo())</script></b>."
 ) 
);

  $langs["pa"] = $skin_pa;
?>
