<?php
// $Id: pl.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language: Polish
// ENCODING: UTF-8
// AUTHOR: Ludwik Trammer <ludwik@trammer.pl>

$skin_pl = array( 

"label" => 
 array ( 
  "about" => "informacje"
 ,"back" => "Wstecz"
 ,"changeLang" => "Zmień Język"
 ,"date" => "Data"
 ,"delete" => "USUŃ"
 ,"doclick" => "Kliknij"
 ,"enter" => "Idź"
 ,"feeds" => "Kanały RSS"
 ,"from" => "Od"
 ,"furtherHelp" => "Dalsze informacje"
 ,"have" => "Masz"
 ,"here" => "tu"
 ,"howto" => "Jak korzystać z __PM__"
 ,"logout" => "Wyloguj"
 ,"mails" => "wiadomości"
 ,"message" => "Wiadomość"
 ,"please" => "Proszę"
 ,"save" => "zapisz"
 ,"step" => "Krok"
 ,"sorry" => "Przykro mi"
 ,"subject" => "Temat"
 ,"toretry" => "ponów"
 ,"viewRawmail" => "Pokaż źródło"
 ,"welcome" => "Witaj"
 ,"welcometo" => "Witaj w __PM__"
 ) 

, "locale" => 
 array (
  "charset" => "UTF-8"
 ,"lang" => "pl"
 )

, "help" => 
 array (
  "404" => "Strony nie znaleziono!<p />Spróbuj"
 ,"500" => "Naszemu serwerowi nie spodobało się twoje zapytanie, albo coś poszło nie tak"
 ,"saveMail" => "Pozwala zapisać wiadomość i zaimportować ją w programie pocztowym"
 ,"viewMail" => "Zobacz oryginalne źródło wiadomości"
 ,"deleteMail" => "Usuń wiadomość z systemu"
 )

, "text" => 
 array ( 
  "about.feeds" => "Kanały RSS 2.0 są dostępne wszędzie gdzie znajduje się pomarańczowe logo <span class='rss'>RSS 2.0</span>."
 ,"about.feeds.url" => "Ogólny format adresów kanałów RSS to <b>http://www.pookmail.com/rss/nazwa_konta.xml</b>"
 ,"about.feeds.aggregator" => "Aby dodać wybrany kanał RSS PookMail.com do swojego <a href='http://en.wikipedia.org/wiki/News_aggregator'>czytnika RSS</a>"
 ,"about.feeds.aggregatorStep1" => "Skopiuj adres związany z interesującym Cię kontem."
 ,"about.feeds.aggregatorStep2" => "Wklej adres w czytniku RSS."
 ,"about.furtherHelp" => "Pytania, komentarze i informacje o błędach można przesyłać pod adres <b><script type='text/javascript'>document.write(foo())</script></b>."
 ,"deleteKO" => "Wiadomość nie mogła zostać usunięta."
 ,"deleteOK" => "Wiadomość została usunięta."
 ,"howtostep1" => "Zamiast podawać przy rejestracji w każdym serwisie prawdziwy adres e-mail po prostu wpisz tam jakikolwiek adres w domenie <i>@pookmail.com</i>.<br />Przykład: <b>dajcie_mi_spokoj@pookmail.com</b>"
 ,"howtostep2" => "Poczekaj na dojście wiadomości."
 ,"howtostep3" => "Zaloguj się do PookMail.com poprzez wpisanie loginu z wymyślonego wcześniej adresu e-mail (na przykład <b>dajcie_mi_spokoj</b>) do formularza logowania i kliknij <kbd>Idź</kbd>"
 ,"howtostep4" => "Po 24 godzinach wiadomości powiązane z Twoim loginem zostaną usunięte z systemu."
 ,"whatispookmail" => "<b>PookMail.com</b> jest systemem <i>dynamicznych kont pocztowych</i>. Pozwoli ci ominąć podawanie adresu e-mail w podejrzanych serwisach internetowych.<p />Jest <b>prosty, anonimowy i fajny</b>! Po prostu wymyśl dowolną nazwę i zaczynaj! "
 ,"rsssubscription" => "Zasubskrybuj kanał RSS PookMail aby otrzymywać wiadomości bezpośrednio na pulpit!"
 ,"rss.desc" => "Kanał RSS Pookmail.com pozwala na otrzymywanie informacji o nowych wiadomościach na dowolnym koncie PookMail."
 ,"request4trans" => "<b>Do you want to see P<font color='red'>o</font><font color='blue'>o</font>kMail&#8482; in your own language?</b> <br /><br /> We are looking for translators who would like to help us transtalating this service to others languages. If you like to collaborate, please send an email to <b><script type='text/javascript'>document.write(foo())</script></b>."
 ) 
);

  $langs["pl"] = $skin_pl;
?>
