<?php
// $Id: pt_br.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language: Brazilian
// ENCODING: ISO-88591
// AUTHOR: mass murderer <mass.murderer@gmail.com>

$skin_ptbr = array( 

"label" => 
 array ( 
  "about"   => "sobre"
 ,"back"   => "Voltar"
 ,"changeLang" => "Mudar Linguagem"
 ,"date" => "Data"
 ,"delete" => "Apagar"
 ,"doclick" => "clickar"
 ,"enter" => "Ir"
 ,"from" => "De"
 ,"furtherHelp" => "Ajuda Adicional"
 ,"have" => "Voc&ecirc; tem"
 ,"here" => "aqui"
 ,"howto" => "Como usar __PM__"
 ,"logout" => "Sair"
 ,"mails" => "mails"
 ,"message" => "Mensagem"
 ,"please" => "Por favor"
 ,"save" => "gravar"
 ,"step" => "Passo"
 ,"sorry" => "Desculpe"
 ,"subject" => "Assunto"
 ,"toretry" => "tentar"
 ,"viewRawmail" => "Ver mensagem crua"
 ,"welcome" => "Bem-vindo"
 ,"welcometo" => "Bem-vindo ao __PM__"
 ) 

, "locale" => 
 array (
  "charset" => "ISO-8859-1"
 ,"lang" => "pt_br"
 )

, "help" => 
 array (
  "404" => "A p&aacute;gina requerida n&atilde;o foi encontrada<p />Talvez possa encontrar em"
 ,"500" => "Nosso servidor encontrou erro em sua requisi&ccedil;&atilde;o."
 ,"saveMail" => "Aceita voc&ecirc; gravar essa mensagem e importa-la pelo seu cliente de e-mail favorito."
 ,"viewMail" => "Voc&ecirc; pode ver a mensagem crua (sem tratamento)"
 ,"deleteMail" => "Remove o mail do sistema."
)

, "text" => 
 array ( 
  "about.feeds" => "RSS 2.0 feeds est&atilde;o dispon&iacute;veis onde voc&ecirc; o logotipo do <span class='rss'>RSS 2.0</span>, da cor laranja."
 ,"about.feeds.url" => "O formato geral da URL RSS &eacute;  http://www.pookmail.com/rss/email_account.xml"
 ,"about.feeds.aggregator" => "Olhar um dos PookMail.com feeds no seu <a href='http://en.wikipedia.org/wiki/News_aggregator'>agregador RSS</a>."
 ,"about.feeds.aggregatorStep1" => "Copie a URL/atalho que corresponde &agrave; conta de seu interesse."
 ,"about.feeds.aggregatorStep2" => "Cole a URL em seu leitor, agregador, RSS."
 ,"about.furtherHelp" => "Por favor envie perguntas, coment&aacute;rios e relat&oacute;rio de bugs para <b><script type='text/javascript'>document.write(foo())</script></b>."
 ,"deleteKO" => "Sua conta de email n&atilde;o pode ser removida."
 ,"deleteOK" => "Sua conta de email foi removida."
 ,"howtostep1" => "Ao inv&eacute;s de sair dando seu endere&ccedil;o de email para qualquer site na internet, apenas pense em um nome imagin&aacute;rio para <i>@pookmail.com</i>.<br />Exemplo: <b>naopertube@pookmail.com</b>"
 ,"howtostep2" => "Espere seu email chegar."
 ,"howtostep3" => "Entre em PookMail.com digitando seu nome de email imagin&aacute;rio (<b>naopertube</b>) na caixa de usuario e clique em <kbd>Ir</kbd>"
 ,"howtostep4" => "Depois de 24 horas, o seu email imagin&aacute;rio ser&aacute; totalmente apagado do sistema."
 ,"whatispookmail" => "<b>PookMail.com</b> &eacute; um sistema de <i>conta de email descart&aacute;vel</i>. Use PookMail.com para evitar de dar seu endere&ccedil;o de email pessoal aos sites suspeitos.<p />&Eacute; muito <b>f&aacute;cil, an&ocirc;nimo e engra&ccedil;ado</b>! Apenas pense em um nome e PRONTO!"
 ,"rsssubscription" => "Inscreva-se ao RSS feed do PookMail para pegar emails direto de seu desktop."
 ,"rss.desc" => "Pookmail.com RSS feed - Com ele voc&ecirc; pode checar qualquer conta de email do Pookmail."
 ,"request4trans" => "<b>Voc&ecirc; quer ver o P<font color='red'>o</font><font color='blue'>o</font>kMail&#8482; em sua pr&oacute;pria linguagem?</b> <br /><br /> Estamos procurando por pessoas que possam traduzir esse servi&ccedil;o para outras linguagens. Se voc&ecirc; quiser colaborar, por favor mande um email para <b><script type='text/javascript'>document.write(foo())</script></b>."
 ) 
);

  $langs["pt_br"] = $skin_ptbr;
?>
