<?php
// $Id: pt_pt.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language: Portuguese
// ENCODING: ISO-88591
// AUTHOR: Pedro Almeida <ferreiradealmeida@gmail.com>

$skin_ptpt = array( 

"label" => 
 array ( 
  "about"   => "sobre"
 ,"back"   => "Voltar"
 ,"changeLang" => "Mudar Linguagem"
 ,"date" => "Data"
 ,"delete" => "Apagar"
 ,"doclick" => "clickar"
 ,"enter" => "Ir"
 ,"from" => "De"
 ,"furtherHelp" => "Ajuda Adicional"
 ,"have" => "Tens"
 ,"here" => "aqui"
 ,"howto" => "Como utilizar o __PM__"
 ,"logout" => "Sair"
 ,"mails" => "mails"
 ,"message" => "Mensagem"
 ,"please" => "Por favor"
 ,"save" => "gravar"
 ,"step" => "Passo"
 ,"sorry" => "Desculpe"
 ,"subject" => "Assunto"
 ,"toretry" => "tentar"
 ,"viewRawmail" => "Ver mensagem crua"
 ,"welcome" => "Bem-vindo"
 ,"welcometo" => "Bem-vindo ao __PM__"
 ) 

, "locale" => 
 array (
  "charset" => "ISO-8859-1"
 ,"lang" => "pt"
 )

, "help" => 
 array (
  "404" => "A p&aacute;gina pedida n&atilde;o foi encontrada. <p />Talvez a possa encontrar em"
 ,"500" => "O nosso servidor encontrou um erro no seu pedido."
 ,"saveMail" => "Aceita gravar esta mensagem e import&aacute;-la no seu cliente de e-mail favorito."
 ,"viewMail" => "Voc&ecirc; pode ver a mensagem crua (sem tratamento)"
 ,"deleteMail" => "Apague o mail do sistema."
)

, "text" => 
 array ( 
  "about.feeds" => "Os feeds RSS 2.0 est&atilde;o dispon&iacute;veis sempre que vir o &iacute;cone laranja <span class='rss'>RSS 2.0</span>, da cor laranja."
 ,"about.feeds.url" => "O formato geral da URL RSS &eacute;  http://www.pookmail.com/rss/email_account.xml"
 ,"about.feeds.aggregator" => "Para ver um dos feeds do PookMail.com no seu <a href='http://en.wikipedia.org/wiki/News_aggregator'>leitor de RSS</a>."
 ,"about.feeds.aggregatorStep1" => "Copie o URL/atalho RSS que corresponde &agrave; conta de seu interesse."
 ,"about.feeds.aggregatorStep2" => "Cole o URL no seu leitor/ agregador de RSS."
 ,"about.furtherHelp" => "Por favor envie perguntas, coment&aacute;rios, relat&oacute;rio de bugs, etc, directamente para <b><script type='text/javascript'>document.write(foo())</script></b>."
 ,"deleteKO" => "A sua conta de email n&atilde;o pode ser removida."
 ,"deleteOK" => "A sua conta de email foi removida."
 ,"howtostep1" => "Em vez de deixares o teu endere&ccedil;o de email em qualquer site na internet, pense apenas num nome imagin&aacute;rio para <i>@pookmail.com</i>.<br />Exemplo: <b>naochateiem@pookmail.com</b>"
 ,"howtostep2" => "Espere que o teu email chegue."
 ,"howtostep3" => "Entra em PookMail.com inserindo o teu nome de email imagin&aacute;rio (<b>naochateiem</b>) na caixa de login e cliqua em <kbd>Entrar</kbd>"
 ,"howtostep4" => "Ap&oacute;s 24 horas, o teu email imagin&aacute;rio ser&aacute; totalmente apagado do sistema."
 ,"whatispookmail" => "<b>PookMail.com</b> &eacute; uma <i>conta de email descart&aacute;vel</i>. Utiliza o PookMail.com para evitar deixar o teu endere&ccedil;o de email pessoal em sites suspeitos.<p />&Eacute; muito <b>f&aacute;cil, an&ocirc;nimo e engra&ccedil;ado</b>! Pense apenas num nome e PRONTO!"
 ,"rsssubscription" => "Inscreva-se no RSS feed do PookMail para recever emails directamente no teu PC."
 ,"rss.desc" => "Pookmail.com RSS feed - Com ele podes verificar qualquer conta de email do Pookmail."
 ,"request4trans" => "<b>Queres ver o P<font color='red'>o</font><font color='blue'>o</font>kMail&#8482; na tua pr&oacute;pria linguagem?</b> <br /><br /> Estamos &agrave; procura de pessoas que possam traduzir este servi&ccedil;o para outras linguagens. Se quiseras colaborar, por favor envia um email para <b><script type='text/javascript'>document.write(foo())</script></b>."
 ) 
);

  $langs["pt_pt"] = $skin_ptpt;
?>
