<?php
// $Id: ro.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language: Romanian
// ENCODING: ISO-88591
// AUTHOR: Pantea Liviu <puiahappy@gmail.com>

$skin_ro = array( 

"label" => 
 array ( 
  "about" => "despre"
 ,"back" => "Inapoi"
 ,"date" => "Data"
 ,"delete" => "sterge"
 ,"doclick" => "click"
 ,"enter" => "Intra"
 ,"feeds" => "via RSS"
 ,"from" => "de la"
 ,"furtherHelp" => "Mai Mult Ajutor"
 ,"have" => "aveti"
 ,"here" => "aici"
 ,"howto" => "Instructiuni __PM__"
 ,"logout" => "Iesire"
 ,"mails" => "scrisori"
 ,"message" => "mesaje"
 ,"please" => "Va rog"
 ,"save" => "salveaza"
 ,"step" => "Pas"
 ,"sorry" => "Imi pare rau"
 ,"subject" => "subiect"
 ,"toretry" => "pentru a reincerca"
 ,"viewRawmail" => "citeste scrisoarea primita"
 ,"welcome" => "Bine ati venit"
 ,"welcometo" => "Bine ati venit la __PM__"
 ) 

, "locale" => 
 array (
  "charset" => "ISO-8859-1"
 ,"lang" => "ro"
 )

, "help" => 
 array (
  "404" => "Pagina cautata nu a fost gasita!<p />Poate ar trebui sa incerci la"
 ,"500" => "Serverul nostru nu a putut interpreta cererea sau a fost ceva neregula."
 ,"saveMail" => "Iti permite sa salvezi acesta scrisoare, si sa o descarci in clientul tau favorit de mail"
 ,"viewMail" => "Aici poti vedea scrisoarea raw"
 ,"deleteMail" => "Sterge scrisoarea din sistem"
 )

, "text" => 
 array ( 
  "about.feeds" => "RSS 2.0 este disponibil oriunde vezi logoul portocaliu <span class='rss'>RSS 2.0</span>."
 ,"about.feeds.url" => "Formatul general al adreselor RSS este <b>http://www.pookmail.com/rss/contul_tau.xml</b>"
 ,"about.feeds.aggregator" => " Citeste unul din RSS-urile PookMail.com in <a href='http://en.wikipedia.org/wiki/News_aggregator'>RSS Aggregator-ul</a> tau"
 ,"about.feeds.aggregatorStep1" => "Copiaza URL-ul care corespunde adresei tale."
 ,"about.feeds.aggregatorStep2" => "Lipeste URL-ul in cititorul tau."
 ,"about.furtherHelp" => "Va rog trimiteti intrebarile, comentariile, erorile etc. la adresa <b><script type='text/javascript'>document.write(foo())</script></b>."
 ,"deleteKO" => "Scrisoarea nu poate fi stearsa."
 ,"deleteOK" => "Scrisoarea a fost stearsa."
 ,"howtostep1" => "In loc de a da adresa reala de mail la toata lumea, mai bine alegeti un nume <i>@pookmail.com</i>.<br />Exemplu: <b>dontbotherme@pookmail.com</b>"
 ,"howtostep2" => "Asteapta ca scrisoarea sa iti ajunga."
 ,"howtostep3" => "Intra la PookMail.com scriind numele ales (<b>dontbotherme</b>) in casuta de adresa, si apasati <kbd>Intra</kbd>"
 ,"howtostep4" => "Dupa 24 ore, adresa asociata cu numele ales se v-a sterge din sistem."
 ,"whatispookmail" => "<b>PookMail.com</b> este o <i>adresa mereu disponibila.</i> Foloseste PookMail.com pentru a evita sa iti dai adresa ta reala unor situri suspecte.<p />Este foarte <b>usor, sigur si distractiv</b>! Doar alege un nume si intra!"
 ,"rsssubscription" => "Prin RSS-urile de la PookMail primesti scrisorile direct la tine pe desktop!"
 ,"rss.desc" => "Prin RSS-urile de la PookMail vezi toate mesajele care iti intra in contul tau."
 ,"request4trans" => "<b>Vrei sa vezi P<font color='red'>o</font><font color='blue'>o</font>kMail&#8482; in limba ta?</b> <br /><br /> Noi cautam translatori care doresc sa ne ajute sa traducem acest serviciu in alte limbi. Daca ati vrea sa colaborati, va rog trimiteti o scrisoare la adresa <b><script type='text/javascript'>document.write(foo())</script></b>."
 ) 
);

  $langs["ro"] = $skin_ro;
?>
