<?php
// $Id: ru.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language: Russian
// ENCODING: UTF-8
// AUTHOR: Maxx_Da_Fly <mdf@e-baka.net>
// AUTHOR: Vitaly <vmagnit@gmail.com>


$skin_ru = array( 

"label" => 
 array ( 
  "about" => "о сервисе"
 ,"back" => "Назад"
 ,"changeLang" => "Сменить язык"
 ,"date" => "Дата"
 ,"delete" => "Удалить"
 ,"doclick" => "нажать"
 ,"enter" => "Вперед!"
 ,"feeds" => "Feeds"
 ,"four" => "4"
 ,"from" => "От"
 ,"furtherHelp" => "Дополнительная помощь"
 ,"have" => "У вас есть"
 ,"here" => "здесь"
 ,"howto" => "Как пользоваться __PM__"
 ,"logout" => "Выйти"
 ,"mails" => "письма"
 ,"message" => "Сообщение"
 ,"one" => "1"
 ,"please" => "Пожалуйста"
 ,"save" => "сохранить"
 ,"step" => "Шаг"
 ,"sorry" => "Извините"
 ,"subject" => "Тема"
 ,"three" => "3"
 ,"toretry" => "повторить"
 ,"two" => "2"
 ,"viewRawmail" => "Смотреть письмо с заголовками"
 ,"welcome" => "Добро пожаловать"
 ,"welcometo" => "Добро пожаловать в __PM__"
 )

, "locale" => 
 array (
  "charset" => "UTF-8"
 ,"lang" => "ru"
 )

, "help" => 
 array (
  "404" => "Запрошеная страница не найдена!<p />Попробуйте начать серфинг по сайту с"
 ,"500" => "нашему серверу не понравился ваш запрос."
 ,"saveMail" => "Позволяет вам сохранить это письмо и импортировать его в ваш любимый почтовый клиент"
 ,"viewMail" => "Вы можете видеть письмо полностью, с заголовками"
 ,"deleteMail" => "Удаляет письмо из системы"
 )

, "text" => 
 array ( 
  "about.feeds" => "потоки RSS 2.0 доступны там, где вы видите оранжевый логотип <span class='rss'>RSS 2.0</span>."
 ,"about.feeds.url" => "Основной формат RSS-адресов:<b>http://www.pookmail.com/rss/email_account.xml</b>"
 ,"about.feeds.aggregator" => " видеть один из PookMail.com RSS-потоков в вашем <a href='http://en.wikipedia.org/wiki/News_aggregator'>RSS-ридере</a>"
 ,"about.feeds.aggregatorStep1" => "Скопируйте URL, соответствующий интересующему вас аккаунту."
 ,"about.feeds.aggregatorStep2" => "Вставьте URL в ваш RSS-ридер."
 ,"about.furtherHelp" => "Вопросы, комментарии, баг-репорты и т. п. шлите прямо нам по адресу<b><script type='text/javascript'>document.write(foo())</script></b>."
 ,"deleteKO" => "Ваше письмо не может быть удалено"
 ,"deleteOK" => "Ваше письмо удалено"
 ,"howtostep1" => "Используйте временный email-адрес в системе <i>@pookmail.com</i> вместо того, чтобы оставлять свой реальный адрес на неблагонадежных сайтах.<br />Например: <b>nebespokoytemenya@pookmail.com</b>"
 ,"howtostep2" => "Ожидайте, получения письма."
 ,"howtostep3" => "Войдите в PookMail.com введя ваш временный почтовый адрес (<b>nebespokoytemenya</b>) в форме входа и нажмите <kbd>Вперед</kbd>"
 ,"howtostep4" => "Письмо, ассиоциированое с вашим именем, будет удалено из системы через 24 часа."
 ,"whatispookmail" => "<b>PookMail.com</b> - система <i>одноразовых почтовых аккаунтов</i>. Используйте PookMail.com для того, чтобы не давать свой собственый почтовый адрес подозрительным вебсайтам.<p />Это <b>удобно и анонимно</b>!  Просто придумайте имя!"
 ,"rsssubscription" => "Подпишитесь на RSS-поток вашего почтового ящика PookMail чтобы получать письма прямо в программу-агрегатор"
 ,"rss.desc" => "RSS-потоки PookMail позволяют вам знать о новых письмах, пришедших на ваш аккаунт."
 ,"request4trans" => "<b>Хотите видеть P<font color='red'>o</font><font color='blue'>o</font>kMail&#8482; на вашем родном языке?</b> <br /><br /> Мы ищем переводчиков, которые могли бы помочь нам в переводе этого сервиса на другие языки. Если вы готовы сотрудничать, пожалуйста, пошлите письмо на <b><script type='text/javascript'>document.write(foo())</script></b>."
 ) 
);

  $langs["ru"] = $skin_ru;
?>
