<?php
// $Id: sk.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language: Slovak
// ENCODING: ISO-8859-2
// AUTHOR: shinnoki <shinnoki@seznam.cz>

$skin_sk = array( 

"label" => 
 array ( 
  "about" => "O programe"
 ,"back" => "Spat"
 ,"changeLang" => "Zmenit Jazyk"
 ,"date" => "Datum"
 ,"delete" => "Vymazat"
 ,"doclick" => "Kliknut"
 ,"enter" => "Vstupit"
 ,"from" => "Od"
 ,"furtherHelp" => "Viac Pomoci"
 ,"have" => "Mate"
 ,"here" => "tu"
 ,"howto" => "Ako pouzit __PM__"
 ,"logout" => "Odpojit"
 ,"mails" => "maily"
 ,"message" => "sprava"
 ,"please" => "Prosim"
 ,"save" => "ulozit"
 ,"step" => "Krok"
 ,"sorry" => "prepaete"
 ,"subject" => "Predmet"
 ,"toretry" => "opakovat"
 ,"viewRawmail" => "Otvorit surovy email"
 ,"welcome" => "Vitajte"
 ,"welcometo" => "Vitajte v __PM__"
 ) 

, "locale" => 
 array (
  "charset" => "ISO-8859-2"
 ,"lang" => "sk"
 )

, "help" => 
 array (
  "404" => "Stranka ktoru hadate nebola najdena!<p />Mozno by ste mali zaeat"
 ,"500" => "nas server nevedel spracovat vasu poziadavku alebo sa stalo nieeo zle."
 ,"saveMail" => "Umozouje Vam ulozit tento email, a importovat pomocou Vasho emailoveho klienta"
 ,"viewMail" => "Mozete vidiet original emailu"
 ,"deleteMail" => "Odstraouje email z tohto systemu"
 )

, "text" => 
 array ( 
  "about.feeds" => "RSS 2.0 prostriedky sa nachadzaju kdekovek vidite oranzove <span class='rss'>RSS 2.0</span> logo."
 ,"about.feeds.url" => "Hlavny format RSS adresy je <b>http://www.pookmail.com/rss/email_account.xml</b>"
 ,"about.feeds.aggregator" => "Prezrite si jeden z PookMail.com feeds vo vasom <a href='http://en.wikipedia.org/wiki/News_aggregator'>RSS Aggregatory</a>"
 ,"about.feeds.aggregatorStep1" => "Kopirovat jednu adresu/skratku ktora zodpoveda uctu, ktory Vas zaujímva."
 ,"about.feeds.aggregatorStep2" => "Skopirovat URL do pola pre URL adresy."
 ,"about.furtherHelp" => "Prosim zasielajte otazky, komentare, chyby atd priamo na <b><script type='text/javascript'>document.write(foo())</script></b>."
 ,"deleteKO" => "Vas email nemoze byt zmazany"
 ,"deleteOK" => "Vas email bol zmazany"
 ,"howtostep1" => "Namiesto toho, aby ste davali vasu emailovu adresu na kazdu stranku na svete, staci ked si vymyslite imaginarne meno pre <i>@pookmail.com</i>.<br />Napriklad: <b>neotravujtema@pookmail.com</b>"
 ,"howtostep2" => "Vyckajte kym Vam dojde email."
 ,"howtostep3" => "Pripojte sa na PookMail.com a vlozenim imaginarneho emailoveho mena (<b>neotravujtema</b>) do prazdneho okna, a kliknite <kbd>Vstupit</kbd>"
 ,"howtostep4" => "Po 24 hodinach, email spojeny s vasim pristupovym menom bude zmazany z nasho systemu."
 ,"whatispookmail" => "<b>PookMail.com</b> je <i>odpadovy emailovy</i> system. Pouzite PookMail.com na to, aby ste nemuseli zadavat vasu osobnu emailovu adresu podozrivym strankam.<p />Je to velmi <b>jednoduche, anonymne a zabavne</b>! Proste si vymyslite meno a Vstupte!"
 ,"rsssubscription" => "Predpladte si PookMailsky RSS feeds a ziskajte moznost dorucenia emailov priamo na Vasu plochu!"
 ,"rss.desc" => "Pookmail.com RSS feed Vam umozouje vediet, kedy mate prichodzie emaily na hocijaky ueet na pookmail."
 ,"request4trans" => "<b>Chcete vidiet P<font color='red'>o</font><font color='blue'>o</font>kMail&#8482; vo vasom jazyku?</b> <br /><br /> Hladame prekladacov, ktory by nam pomahali prekladat nasu sluzbu do inych jazykov. Ak by ste chceli spolupracovat, poslite email na <b><script type='text/javascript'>document.write(foo())</script></b>."
 ) 
);

  $langs["sk"] = $skin_sk;
?>
