<?php
// $Id: sv.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language: Swedish
// ENCODING: ISO-8859-1
// AUTHOR: Hyter Hyterson <hyter@hotmail.com>


$skin_sv = array( 

"label" => 
 array ( 
  "about" => "Om"
 ,"back" => "Tillbaka"
 ,"changeLang" => "Ändra språk"
 ,"date" => "Datum"
 ,"delete" => "Radera"
 ,"doclick" => "Klicka"
 ,"enter" => "Kör"
 ,"feeds" => "Feeds"
 ,"four" => "fyra"
 ,"from" => "Från"
 ,"furtherHelp" => "Mer hjälp"
 ,"have" => "Du har"
 ,"here" => "Här"
 ,"howto" => "Anvisningar __PM__"
 ,"logout" => "Logga ut"
 ,"mails" => "mails"
 ,"message" => "Meddelande"
 ,"one" => "ett"
 ,"please" => "Var god"
 ,"save" => "Spara"
 ,"step" => "Steg"
 ,"sorry" => "Tyvärr"
 ,"subject" => "Ämne"
 ,"three" => "tre"
 ,"toretry" => "Försök igen"
 ,"two" => "två"
 ,"viewRawmail" => "Visa källmeddelande"
 ,"welcome" => "Välkommen"
 ,"welcometo" => "Välkommen till __PM__"
 )

, "locale" => 
 array (
  "charset" => "ISO-8859-1"
 ,"lang" => "sv"
 )

, "help" => 
 array (
  "404" => "Sidan du söker hittades inte!<p />Försök att starta om vid"
 ,"500" => "Servern godkände inte din förfågan eller ett fel uppstod."
 ,"saveMail" => "Spara detta mail, och importera det med din favorit e-post klient"
 ,"viewMail" => "Du kan kontrollera källmeddelande"
 ,"deleteMail" => "Tar bort e-postmeddelande från systemet"
 )

, "text" => 
 array ( 
  "about.feeds" => "RSS 2.0 feeds är tillgängliga där du ser en orange <span class='rss'>RSS 2.0</span> logo."
 ,"about.feeds.url" => "Standardformat för RSS url:s är <b>http://www.pookmail.com/rss/e-post_konto.xml</b>"
 ,"about.feeds.aggregator" => " Läs PookMail.com feeds i din <a href='http://en.wikipedia.org/wiki/News_aggregator'>RSS läsare</a>"
 ,"about.feeds.aggregatorStep1" => "Kopiera den URL/genväg som hör ihop med det konto som intresserar dig.."
 ,"about.feeds.aggregatorStep2" => "Klistra in URL i din läsare."
 ,"about.furtherHelp" => "Skicka gärna frågor, kommentarer, bug rapporter mm.  direkt till oss på <b><script type='text/javascript'>document.write(foo())</script></b>."
 ,"deleteKO" => "Meddelandet kan ej tas bort"
 ,"deleteOK" => "Meddelandet har raderats"
 ,"howtostep1" => "Istället för att lämna ut din e-post adress till varenda webbsida på jorden, använd ett påhittat namn för <i>@pookmail.com</i>.<br />Exempel: <b>dontbotherme@pookmail.com</b>"
 ,"howtostep2" => "Vänta på ditt e-post meddelande."
 ,"howtostep3" => "Logga in till PookMail.com genom att skriva in ditt påhittade e-post namn (<b>dontbotherme</b>) i logga in rutan, och klicka <kbd>Kör</kbd>"
 ,"howtostep4" => "Efter 24 timmar kommer e-post meddelandet bli raderat från systemet."
 ,"whatispookmail" => "<b>PookMail.com</b> är ett <i>skräp e-post konto</i> system. Använd PookMail.com för att slippa lämna ut din personliga e-post adress på misstänkta webbsidor.<p />It's very <b>enkelt anonymt och roligt</b>! Hitta bara på ett namn och kör igång!"
 ,"rsssubscription" => "Prenumerera på PookMail's RSS feeds för att få e-post meddelanden levererade direkt till din dator!"
 ,"rss.desc" => "Pookmail.com RSS feed låter dig kontrollera inkommande e-post på vilket PookMail konto som helst."
 ,"request4trans" => "<b>Vill du se P<font color='red'>o</font><font color='blue'>o</font>kMail&#8482; på ditt eget språk?</b> <br /><br /> Vi söker översättare som vill hjälpa oss att översätta denna service till andra språk. Om du vill delta, var god och skicka e-post till <b><script type='text/javascript'>document.write(foo())</script></b>."
 ) 
);

  $langs["sv"] = $skin_sv;
?>
