<?php
// $Id: tr.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language: Turkish
// ENCODING: ISO-28599
// AUTHOR: Salih Saricam <saricam@gmail.com>

$skin_tr = array( 

"label" => 
 array ( 
  "about" => "hakkýnda"
 ,"back" => "Geri"
 ,"date" => "Tarih"
 ,"delete" => "Sil"
 ,"doclick" => "Týkla"
 ,"enter" => "Git"
 ,"feeds" => "Beslemeler"
 ,"from" => "Kimden"
 ,"furtherHelp" => "Daha Fazla Yardým"
 ,"have" => "Gelen"
 ,"here" => "burayý"
 ,"howto" => "Nasýl kullanýrým __PM__"
 ,"logout" => "Çýkýþ"
 ,"mails" => "adet posta"
 ,"message" => "Mesaj"
 ,"please" => "Lütfen"
 ,"save" => "kaydet"
 ,"step" => "Aþama"
 ,"sorry" => "Üzgünüm"
 ,"subject" => "Baþlýk"
 ,"toretry" => "yeniden denemek için"
 ,"viewRawmail" => "Taslak Mesaj"
 ,"welcome" => "Hoþgeldiniz"
 ,"welcometo" => "__PM__ 'a hoþgeldiniz"
 ) 

, "locale" => 
 array (
  "charset" => "ISO-28599"
 ,"lang" => "tr"
 )

, "help" => 
 array (
  "404" => "Aradýðýnýz sayfa bulunamadý"
 ,"500" => "sunucumuz sizin isteðinizi kabul etmedi ya da yanlýþ giden birþeyler var"
 ,"saveMail" => "Bu mesajý kaydetmenize ve kullandýðýnýz e-posta yazýlýmýna yüklemenize olanak tanýr"
 ,"viewMail" => "Orijinal taslak mesajý görebilirsiniz"
 ,"deleteMail" => "Mesajý sistemden siler"
 )

, "text" => 
 array ( 
  "about.feeds" => "<span class='rss'>RSS 2.0</span> logosunu gördüðünüz yerlerde RSS 2.0 beslemesi açýktýr."
 ,"about.feeds.url" => "RSS adreslerinin geneli <b>http://www.pookmail.com/rss/email_account.xml</b> þeklindedir"
 ,"about.feeds.aggregator" => "PookMail.com RSS beslemelerinden birisiniz <a href='http://en.wikipedia.org/wiki/News_aggregator'>RSS Aggregator</a> programýnýzda izleyin"
 ,"about.feeds.aggregatorStep1" => "Sizi ilgilendiren hesaba ait adresi/kýsayolu kopyalayýn."
 ,"about.feeds.aggregatorStep2" => "Adresi okuyucunuza yapýþtýrýn."
 ,"about.furtherHelp" => "Sorularýnýzý, yorumlarýnýzý, açýklarý vb. þeyleri <b><script type='text/javascript'>document.write(foo())</script></b> adresinden doðrudan bize bildiriniz."
 ,"deleteKO" => "Postanýz silinemedi"
 ,"deleteOK" => "Postanýz silindi"
 ,"howtostep1" => "Dünyadaki bütün sitelere gerçek posta adresinizi vermek yerine, <i>@pookmail.com</i> þeklinde hayali bir adres yaratýn. <br />Örnek: <b>benirahatsizetme@pookmail.com</b>"
 ,"howtostep2" => "Postanýzýn ulaþmasý için bekleyin."
 ,"howtostep3" => "Hayali posta adresinizi (<b>benirahatsizetme</b>) giriþ formuna yazarak Pookmail.com 'a giriþ yapýn <kbd>Git</kbd>"
 ,"howtostep4" => "Giriþ adýnýzýla iliþkilendirilen posta hesabýnýz 24 saat sonunda silinecektir."
 ,"whatispookmail" => "<b>PookMail.com</b> bir <i>kullan-at posta hesabý</i> sistemidir. Kiþisel posta adresinizi þüpheli sitelere vermeyi önlemek için Pookmail.com'u kullanýn.<p />Bu çok <b>kolay, belirsiz ve neþeli</b>! Sadece ismi düþün ve GÝT!"
 ,"rsssubscription" => "Ulaþan postalarý beklemeden almak için Pookmail.com'un RSS beslemesine kayýt olun!"
 ,"rss.desc" => "Pookmail.com RSS beslemesi herhangi bir Pookmail.com hesabýna gelen postalarý kontrol etmenize olanak tanýr.."
 ,"request4trans" => "<b>P<font color='red'>o</font><font color='blue'>o</font>kMail&#8482 'i kendi dilinizde görmek mi istiyorunuz?</b> <br /><br /> Bu hizmeti diðer dillere çevirebilecek gönüllü kiþiler arýyoruz. Eðer katýlmak isterseniz  <b><script type='text/javascript'>document.write(foo())</script></b> adresine bir posta göndermeniz yeterli."
 ) 
);

  $langs["tr"] = $skin_tr;
?>
