<?php
// $Id: vi.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language: Vietnamese
// ENCODING: UTF-8
// AUTHOR: luan le ba <lebaluan@gmail.com>


$skin_vi = array( 

"label" => 
 array ( 
 "about" => "Xem thêm về trang web"
,"back" => "Trở lại"
,"comingsoon" => "Sắp mở cửa."
,"changeLang" => "Đổi ngôn ngữ"
,"date" => "Ngày"
,"delete" => "Xóa"
,"doclick" => "nhấp"
,"enter" => "Vào"
,"feeds" => "Các bước thực hiện"
,"four" => "4"
,"from" => "Từ"
,"furtherHelp" => "Hỗ trợ thêm"
,"have" => "Bạn có"
,"here" => "ở đây"
,"howto" => "Làm thế nào để sử dụng Pookmail.com"
,"international" => "quốc tế"
,"logout" => "Thoát"
,"mails" => "thư điện tử"
,"message" => "Tin nhắn"
,"one" => "1"
,"please" => "Làm ơn"
,"save" => "lưu"
,"step" => "Bước"
,"sorry" => "Rất tiếc"
,"subject" => "Chủ đề"
,"three" => "3"
,"toretry" => "để thử lại"
,"two" => "2"
,"viewRawmail" => "xem thư dạng thô"
,"welcome" => "Chào mừng"
,"welcometo" => "Chào mừng đến"
 )

, "locale" => 
 array (
  "charset" => "UTF-8"
 ,"lang" => "vi"
 )

, "help" => 
 array (
 "404" => "Trang yêu cầu không được tìm thấy!<p />Có lẽ bạn nên bắt đầu tại"
,"500" => "máy chủ của chúng tôi không thể đáp ứng yêu cầu của bạn hoặc có một lỗi sai."
,"saveMail" => "Cho phép bạn lưu thư này, và nhập nó vào mục email khách ưa thích của bạn."
,"viewMail" => "Bạn có thể xem các thư thô gốc."
,"deleteMail" => "Xóa thư từ hệ thống."
 )

, "text" => 
 array ( 
 "about.feeds" => "Các bước của RSS 2.0  thì có hiệu lực ở bất kì vị trí nào bạn thấy một nhãn RSS 2.0 màu cam."
,"about.feeds.url" => "Ðịnh dạng chung của địa chỉ RSS là  <b>http://www.pookmail.com/rss/email_account.xml</b>"
,"about.feeds.aggregator" => " Ðể xem một trong những bước của PookMail.com thuộc RSS Aggregator của bạn"
,"about.feeds.aggregatorStep1" => "Sao chép URL/biểu tượng phù hợp vài tài khoản mà bạn yêu thích."
,"about.feeds.aggregatorStep2" => "Dán URL này vào trong mục reader của bạn."
,"about.furtherHelp" => "Hãy gởi những câu hỏi, lời nhận xét, những tường thuật về lỗi v.v… trực tiếp đến chúng tôi tại <b><script type='text/javascript'>document.write(foo())</script></b>."
,"about.visitBlog" => "Đến thăm <a id='blog' href='http://pookmail.blogspot.com'>PookMail.com Blog</a> để có được những thông tin mới nhất!"
,"deleteKO" => "Thư của bạn không thể xóa"
,"deleteOK" => "Thư của bạn đã được xóa"
,"dbm.subject" => "Tài khoản ví dụ"
,"dbm.body" => "Tài khoản này chỉ là một ví dụ. Vì sự bảo mật cho bạn, chúng tôi không cho phép đọc hay gửi những thư từ tài khoản này. Hãy thử một cái khác. <p />Cám ơn bạn."
,"howtostep1" => "Thay vì phải gửi địa chỉ email thật của bạn đến mỗi website trên khắp trái đất, chỉ cần nghĩ ra một điạ chỉ tưởng tượng với đuôi miền <i>@pookmail.com</i>.<br />Ví dụ: <b>dunglamphientui@pookmail.com</b>"
,"howtostep2" => "Chờ cho thư của bạn đến."
,"howtostep3" => "Đăng nhập vào PookMail.com bằng cách gõ địa chỉ email tưởng tượng lúc nãy (<b>dunglamphientui</b>) vào khung đăng nhập, và nhấp <kbd>VÀO</kbd>"
,"howtostep4" => "Sau 24 giờ, tất cả thư cùng với tên đăng nhập của bạn sẽ bị xóa từ hệ thống"
,"whatispookmail" => "<b>PookMail.com</b> là một hệ thống <i>tài khoản email</i> dùng một lần.Sử dụng Pookmail.com để tránh dùng địa chỉ email cá nhân của bạn cho những website đáng ngờ.<p />Nó thật sự <b>dễ dàng, kín đáo và tuyệt vời</b>! Chỉ cần nghĩ một cái tên và VÀO!"
,"rsssubscription" => "Hãy đăng kí tại PookMail's RSS feeds để có những email được chuyển trực tiếp đến màn hình của bạn!"
,"rss.desc" => "Pookmail.com RSS feed cho phép bạn biết được tất cả các thư được chuyển vào bất kì tài khoản Pookmail nào."
,"request4trans" => "<b>Bạn có muốn xem P<font color='red'>o</font><font color='blue'>o</font>kMail&#8482; bằng ngôn ngữ của bạn ?</b> <br /><br /> Chúng tôi đang tìm kiếm người phiên dịch có thể giúp chúng tôi dịch trang web này sang ngôn ngữ khác. Nếu bạn có mong muốn trở thàng người cộng tác của chúng tôi, xin hãy vui lòng gửi một email đến <b><script type='text/javascript'>document.write(foo())</script></b>."
,"visitBlog" => "Thăm Bl<font color='blue'>o</font>g <font color='red'>C</font>hính thức!"
 ) 
);

  $langs["vi"] = $skin_vi;
?>
