<?php
// $Id" => "blank.inc,v 1.2 2005/05/21 23:20:12 alex Exp $
// Language" => "Chinese
// ENCODING" => "UTF-8
// AUTHOR" => "Helin Cao <hlcao@mail.ustc.edu.cn>


$skin_zh = array( 

"label" => 
 array ( 
  "about" => "关于"
 ,"back" => "返回"
 ,"changeLang" => "选择语言"
 ,"date" => "日期"
 ,"delete" => "删除"
 ,"doclick" => "点击"
 ,"enter" => "进入!"
 ,"feeds" => "Feeds"
 ,"four" => "四"
 ,"from" => "来自"
 ,"furtherHelp" => "进一步的帮助"
 ,"have" => "你有"
 ,"here" => "这里"
 ,"howto" => "用法 __PM__"
 ,"logout" => "注销"
 ,"mails" => "邮件"
 ,"message" => "消息"
 ,"one" => "一"
 ,"please" => "请"
 ,"save" => "保存"
 ,"step" => "步骤"
 ,"sorry" => "抱歉"
 ,"subject" => "主题"
 ,"three" => "三"
 ,"toretry" => "再试一次"
 ,"two" => "二"
 ,"viewRawmail" => "查看原始信件"
 ,"welcome" => "欢迎"
 ,"welcometo" => "欢迎来到 __PM__"
 )

, "locale" => 
 array (
  "charset" => "UTF-8"
 ,"lang" => "zh"
 )

, "help" => 
 array (
  "404" => "请求链接的网页没找到<p />也许你要从这里开始"
 ,"500" => "我们的服务不能满足你的要求，或者有些地方出错了。"
 ,"saveMail" => "允许你保存邮件，并用你自己喜爱的电子邮件客户端载入它。"
 ,"viewMail" => "你可以看到原始邮件"
 ,"deleteMail" => "从系统中删除邮件"
 )

, "text" => 
 array ( 
  "about.feeds" => "当你看到橙色 <span class='rss'>RSS 2.0</span> 标志的时候，表明RSS 2.0 feeds是可用的。"
 ,"about.feeds.url" => "通用的 RSS 地址是 <b>http://www.pookmail.com/rss/email_account.xml</b>"
 ,"about.feeds.aggregator" => "在你的RSS聚合器中查看PookMail.com的feeds"
 ,"about.feeds.aggregatorStep1" => "复制与你感兴趣的帐户相应的链接。"
 ,"about.feeds.aggregatorStep2" => "将链接粘贴到你的阅读器。"
 ,"about.furtherHelp" => "请把你的问题，建议，漏洞报告发送给我们 <b><script type='text/javascript'>document.write(foo())</script></b>."
 ,"deleteKO" => "你的邮件无法被删除"
 ,"deleteOK" => "你的邮件已经被删除"
 ,"howtostep1" => "无需把你的真实邮件地址给那些不熟悉的网站，只要虚构一个以<i>@pookmail.com</i>为后缀的镜像地址。<br />例如: <b>dontbotherme@pookmail.com</b>"
 ,"howtostep2" => "等待你的邮件到来。"
 ,"howtostep3" => "把你虚构的用户名(<b>dontbotherme</b>)填入登录框，点击<kbd>进入</kbd>，进入PookMail.com"
 ,"howtostep4" => "24小时之后，与你用户名相关的所有邮件将被从系统中清除。"
 ,"whatispookmail" => "<b>PookMail.com</b> 是一个<i>即用即弃的邮件帐户</i>系统。用PookMail.com来避免把你的个人邮件地址给可疑的网站。<p />非常<b>简单，匿名，有趣</b>! 只需想个名字，然后进入!"
 ,"rsssubscription" => "订阅PookMail的RSS feeds，邮件将自动投递到你的电脑上!"
 ,"rss.desc" => "Pookmail.com的RSS feed允许你接收任意PookMail帐户的邮件。"
 ,"request4trans" => "<b>想看到你自己所用语言版本的 P<font color='red'>o</font><font color='blue'>o</font>kMail么?</b> <br /><br /> 我们正在寻找愿意帮助我们把这项服务翻译成各种语言的志愿者。如果你喜欢这种合作方式，请给我们发邮件<b><script type='text/javascript'>document.write(foo())</script></b>."
 ) 
);

  $langs["zh"] = $skin_zh;
?>
