<?php
// $Id: zh_cn.inc,v 1.1.1.1 2007/03/29 18:02:55 alex Exp $
// Language: Chinese Traditional
// ENCODING: UTF-8
// AUTHOR: Kevin <tuwenhsu@gmail.com>


$skin_zhcn = array( 

"label" => 
 array ( 
 "about" => "關於"
,"back" => "回到"
,"changeLang" => "改變語言"
,"date" => "日期"
,"delete" => "刪除"
,"doclick" => "點選"
,"enter" => "確定"
,"feeds" => "來源"
,"four" => "四"
,"from" => "來自"
,"furtherHelp" => "其他幫助"
,"have" => "你有"
,"here" => "這裡"
,"howto" => "如何使用 __PM__"
,"logout" => "登出"
,"mails" => "封信件"
,"message" => "信息"
,"one" => "一"
,"please" => "請你"
,"save" => "儲存"
,"step" => "步驟"
,"sorry" => "對不起"
,"subject" => "主旨"
,"three" => "三"
,"toretry" => "重試"
,"two" => "二"
,"viewRawmail" => "檢視原始信件"
,"welcome" => "歡迎"
,"welcometo" => "歡迎來到 __PM__"
 )

, "locale" => 
 array (
  "charset" => "UTF-8"
 ,"lang" => "zh-cn"
 )

, "help" => 
 array (
 "404" => "你所要求的網頁不存在你應該從(the place to start)開始"
,"500" => "我們的伺服器無法執行你的指令!"
,"saveMail" => "讓你儲存這一封信件並且傳送到你的電腦上"
,"viewMail" => "你可以看到原始信件"
,"deleteMail" => "刪除這封信件"
 )

, "text" => 
 array ( 
 "about.feeds" => "當你看到橙色 RSS 2.0 標誌時，表示RSS 2.0 feeds是可用的。"
,"about.feeds.url" => "通用的 RSS 地址是 <b>http://www.pookmail.com/rss/email_account.xml</b>"
,"about.feeds.aggregator" => "在你的RSS聚合器中查看PookMail.com的feeds"
,"about.feeds.aggregatorStep1" => "複製你感興趣的帳戶的網址."
,"about.feeds.aggregatorStep2" => "把網址貼上你的網路瀏覽器."
,"about.furtherHelp" => "請把你的問题，建議，漏洞報告傳送给我們<b><script type='text/javascript'>document.write(foo())</script></b>."
,"deleteKO" => "你的信件無法被刪除"
,"deleteOK" => "你的信件已經被刪除"
,"howtostep1" => "不需要將你真實的由郵件地址给那些不熟悉的網站，只需要給一個虛構的@pookmail.com郵件地址。例如: dontbotherme@pookmail.com"
,"howtostep2" => "等候你的郵件"
,"howtostep3" => "把你的虛構的用户名(dontbotherme@pookmail.com)填入登入框，點選確定"
,"howtostep4" => "24小時之候，你的用户名和相關的郵件將從系統中刪除。"
,"whatispookmail" => "<b>PookMail.com</b> 是一個 <i>拋棄式的郵件帳戶</i> 系統. 用PookMail.com来避免把你的各人的郵件地址给可疑的網站。.<p />非常 <b>簡單, 匿名, 和有趣</b>! 想好一個名子便登入!"
,"rsssubscription" => "加入到PookMail's RSS feeds你便可將郵件傳送到你的電腦上!"
,"rss.desc" => "Pookmail.com RSS feed 讓你知道信件的來源從任何PookMail帳戶."
,"request4trans" => "<b>想看到你自己所用語言版本的 PookMail嗎? P<font color='red'>o</font><font color='blue'>o</font>kMail&#8482; </b> <br /><br />  我们正在尋找願意幫助我们把這項服務翻譯成各種語言的志願者。如果你喜歡這種合作方式，請聯絡我們在pookinfo@pookmail.com.<b><script type='text/javascript'>document.write(foo())</script></b>."
 ) 
);

  $langs["zh_cn"] = $skin_zhcn;
?>